import React, {useState, useEffect, useRef, useLayoutEffect, useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {chapters,initial,extra} from './content.mjs';
import {drawScene,drawGraph,fmt,liveSentence,isAnimated} from './canvas.mjs';
import {makeQuestion,checkAnswer,substitution} from './exercise.mjs';
import {usePhone,pointInView} from './responsive.jsx';
import {OpticsImagePanel,OpticsSandbox} from './optical-images.jsx';
import {imageOpticsIds} from './optics.mjs';
import {dcIds,dcState} from './electricity.mjs';
import {ElectricitySandbox} from './electrical.jsx';
import {animationPeriod,animationReadout} from './animation.mjs';
import {handlesFor,normalizedPatch,scenePoint,freeFall,clamp} from './interactions.mjs';

function Icon({name,size=18}){const paths={menu:'M4 6h16M4 12h16M4 18h16',move:'M12 3v18M3 12h18M8 7l4-4 4 4M8 17l4 4 4-4M7 8l-4 4 4 4M17 8l4 4-4 4',play:'M8 5l11 7-11 7Z',pause:'M8 5v14M16 5v14',reset:'M4 10a8 8 0 1 1 1 8M4 4v6h6',arrow:'M5 12h14M13 6l6 6-6 6',book:'M12 5v15M3 4l9 1 9-1v15l-9 1-9-1Z'};return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.arrow}/></svg>}
const routeTo = hash => {location.hash=hash};
const labRoute = (c,l,p='lab')=>`chapter/${c.id}/${l.id}/${p}`;
function readSaved(){try{const s=JSON.parse(localStorage.getItem('physics11-progress-v1')||'{}');return {solved:{},notes:{},sourceDone:{},read:{},...s}}catch{return {solved:{},notes:{},sourceDone:{},read:{}}}}
function useClock(running,speed=1){
  const [time,setTime]=useState(0);
  useEffect(()=>{if(!running)return;let id,last=performance.now();function tick(now){const dt=Math.min(Math.max(0,(now-last)/1000),.05);last=now;if(!document.hidden)setTime(t=>t+dt*speed);id=requestAnimationFrame(tick)}id=requestAnimationFrame(tick);return ()=>cancelAnimationFrame(id)},[running,speed]);
  return [time,setTime];
}
function setupCanvas(canvas,w,h){let dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;let ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return ctx}
function Canvas({id,width,height,draw,label}){
  const ref=useRef(null),ctx=useRef(null);
  useLayoutEffect(()=>{ctx.current=setupCanvas(ref.current,width,height)},[width,height]);
  useLayoutEffect(()=>{draw(ctx.current)},[draw]);
  return <canvas id={id} ref={ref} role="img" aria-label={label}/>;
}
export function DragHandles({lab,params,time,setParams,onGrab,onRelease}){
  const active=useRef(null),svg=useRef(null),[dragging,setDragging]=useState(null),phone=usePhone(),viewWidth=phone?530:840;
  const handles=handlesFor(lab,params,time);
  if(!handles.length)return null;
  function move(event){if(!active.current||event.pointerId!==active.current.pointerId)return;const p=pointInView(svg.current.getBoundingClientRect(),event.clientX,event.clientY,viewWidth);setParams(normalizedPatch(lab,active.current.handle.patch(p.x,p.y)))}
  function finish(event,cancel=false){if(!active.current||event.pointerId!==active.current.pointerId)return;const handle=active.current.handle;active.current=null;setDragging(null);event.currentTarget.releasePointerCapture?.(event.pointerId);if(!cancel)onRelease(handle.release)}
  return <svg ref={svg} className="drag-layer" viewBox={`0 0 ${viewWidth} 370`} aria-label="Direct manipulation controls" onPointerMove={move} onPointerUp={finish} onPointerCancel={e=>finish(e,true)}>
    {handles.map(handle=><g key={handle.id} className="drag-handle" data-handle={handle.id} role="button" tabIndex={0} aria-label={`${handle.label}. Arrow keys adjust ${handle.keys[0]}; Shift plus arrows adjusts direction. Enter releases.`}
      onPointerDown={e=>{if(active.current || (e.button!==undefined&&e.button!==0))return;e.preventDefault();svg.current.setPointerCapture?.(e.pointerId);active.current={handle,pointerId:e.pointerId};setDragging(handle.id);onGrab()}}
      onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onRelease(handle.release);return}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();onGrab();let key=handle.keys[e.shiftKey&&handle.keys.length>1?1:0],p=lab.params.find(p=>p.key===key),delta=['ArrowUp','ArrowRight'].includes(e.key)?p.step:-p.step;setParams(normalizedPatch(lab,{[key]:params[key]+delta}))}}>
      <title>{handle.label}</title><circle cx={handle.x} cy={handle.y} r="25" fill="transparent"/><circle className={dragging===handle.id?'grab-ring grabbed':'grab-ring'} cx={handle.x} cy={handle.y} r="13"/><circle cx={handle.x} cy={handle.y} r="4" fill="#173f37"/>
    </g>)}
  </svg>;
}
function Parameter({param:p,value,onChange}){
  const [draft,setDraft]=useState(String(value));
  useEffect(()=>setDraft(String(value)),[value]);
  const commit=()=>{const v=Number(draft);if(draft.trim()&&Number.isFinite(v)){const n=Number(clamp(p.min+Math.round((clamp(v,p.min,p.max)-p.min)/p.step)*p.step,p.min,p.max).toFixed(9));setDraft(String(n));onChange(n)}else setDraft(String(value))};
  return <div className="control"><label htmlFor={'range-'+p.key}><span>{p.label}</span><span className="number-wrap"><input type="number" inputMode="decimal" id={'num-'+p.key} aria-label={`${p.label} in ${p.unit||'dimensionless units'}`} min={p.min} max={p.max} step={p.step} value={draft} onChange={e=>{setDraft(e.target.value);if(e.target.value!==''&&Number.isFinite(Number(e.target.value)))onChange(Number(e.target.value))}} onBlur={commit}/><span>{p.unit}</span></span></label><input type="range" id={'range-'+p.key} aria-label={'Adjust '+p.label} min={p.min} max={p.max} step={p.step} value={value} onChange={e=>onChange(Number(e.target.value))}/><div className="range-bounds"><span>{p.min}</span><span>{p.max}</span></div></div>;
}
function LabTabs({chapter,lab,pane}){return <div className="lab-tabs">{chapter.labs.map(l=><button key={l.id} className={l.id===lab.id?'active':''} data-lab={l.id} onClick={()=>routeTo(labRoute(chapter,l,pane))}>{l.title}</button>)}</div>}
function Lab({chapter,lab,params,setParams,baseline,setBaseline,hide,setHide}){
  const [running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[time,setTime]=useClock(running,speed),[view3d,setView3d]=useState(false),[graphKey,setGraphKey]=useState(lab.params[0].key);
  const [closed,setClosed]=useState(true),[carrier,setCarrier]=useState('conventional');
  const phone=usePhone();
  const dc=dcIds.has(lab.id),electric=dc?dcState(lab,params,closed):null;
  const handles=handlesFor(lab,params,time),value=dc&&lab.id!=='parallel'?electric.current:lab.compute(params),metrics=dc?[['Total current',electric.current,'A'],['Load voltage',electric.voltage,'V'],['Load power',electric.power,'W'],...(lab.id==='parallel'?[['Branch 1',electric.branch1,'A'],['Branch 2',electric.branch2,'A']]:lab.id==='cell'?[['Internal heating',electric.internalPower,'W']]:[])]:extra(lab,params),period=animationPeriod(lab,params);
  const graphDraw=useCallback(c=>drawGraph(c,lab,params,graphKey,baseline,hide,phone?420:840),[lab,params,graphKey,baseline,hide,phone]);
  const grab=()=>{setRunning(false);setTime(0)},release=animate=>{if(animate){setTime(0);setRunning(true)}};
  const change=patch=>{grab();setParams(patch)};
  const reset=()=>{grab();setParams(initial(lab))};
  let comparison='';if(baseline&&!hide){let old=lab.compute(baseline),delta=value-old;comparison=Number.isFinite(value)&&Number.isFinite(old)?`Baseline ${fmt(old)} ${lab.unit}; current ${fmt(value)} ${lab.unit}; change ${fmt(delta)} ${lab.unit}${old!==0?' ('+fmt(delta/Math.abs(old)*100)+'%)':''}.`:'One scenario has no finite numeric result. Compare its ray or image condition instead.'}
  return <>
    <div className="section-row"><h2>The experiment</h2><button id="to-practice" onClick={()=>routeTo(labRoute(chapter,lab,'practice'))}>Try a question →</button></div><LabTabs chapter={chapter} lab={lab} pane="lab"/>
    <section className="lab-card"><header className="lab-header"><h3>{lab.title}</h3><span className="status">{handles.length?'Drag to explore':'Live model'}</span></header>
      <div className="canvas-wrap"><div className="scene-stage"><Canvas id="scene" width={phone?530:840} height={370} label={`${lab.title} visualization. Results and explanation follow below.`} draw={c=>drawScene(c,lab,params,time,view3d,hide,{closed,carrier})}/><DragHandles lab={lab} params={params} time={time} setParams={setParams} onGrab={grab} onRelease={release}/></div>
        <div className="canvas-toolbar">{isAnimated(lab)?<><button id="play" aria-pressed={running} onClick={()=>setRunning(!running)}><Icon name={running?'pause':'play'}/>{running?'Pause':'Play'}</button><button id="restart" onClick={()=>setTime(0)}><Icon name="reset"/>Restart</button><span id="animation-time" className="helper">Animation: {time.toFixed(1)} s</span></>:<span className="helper">Change the values to explore</span>}<button id="predict" aria-pressed={hide} onClick={()=>setHide(!hide)}>{hide?'Reveal outcome':'Prediction mode'}</button>{['orbit','circle'].includes(lab.kind)&&<button id="projection" aria-pressed={view3d} onClick={()=>setView3d(!view3d)}>{view3d?'Plan view':'Perspective view'}</button>}</div>
      </div>
      {dc&&<div className="circuit-controls"><button id="circuit-switch" aria-pressed={closed} onClick={()=>{setClosed(!closed);setTime(0)}}>{closed?'Open switch':'Close switch'}</button><label htmlFor="carrier-mode">Show motion<select id="carrier-mode" value={carrier} onChange={e=>{setCarrier(e.target.value);setTime(0)}}><option value="conventional">Conventional current · gold</option><option value="electrons">Electron drift · blue</option></select></label><span className="helper">Play to follow the charge. Marker speed is proportional to current; it is not a measured drift velocity.</span></div>}
      {isAnimated(lab)&&<div className="playback-controls"><label htmlFor="playback-speed">Playback speed<select id="playback-speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.25}>0.25× · slow motion</option><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><label className="replay-control" htmlFor="replay-position">Replay position<input id="replay-position" type="range" min={0} max={Math.max(.01,period-.01)} step={.01} value={Math.min(time%period,Math.max(.01,period-.01))} onChange={e=>{setRunning(false);setTime(Number(e.target.value))}} aria-label="Scrub animation replay position"/></label><p className="animation-readout" id="animation-readout">{hide?'Reveal the outcome to see the animation’s changing values.':(dc?`${closed?'Closed':'Open'} circuit · I = ${fmt(electric.current)} A · load power = ${fmt(electric.power)} W. ${carrier==='electrons'?'Electrons drift opposite to conventional current.':'Conventional current flows from + to − through the external circuit.'}`:animationReadout(lab,params,time))||'Pause or drag the replay slider to inspect a moment. Changing a physical value resets the animation.'}</p></div>}
      {handles.length>0&&<p className="drag-hint"><Icon name="move"/> {lab.kind==='spring'?'Pull the ring on the mass and release to oscillate.':lab.kind==='projectile'?'Drag the launch arrow’s ring and release to launch.':'Drag the outlined rings to change the physical values.'} Mouse, touch, or keyboard arrows. Formulas and graphs follow your movement.</p>}
      <div className="control-panel">{lab.params.map(p=><Parameter key={p.key} param={p} value={params[p.key]} onChange={v=>change(normalizedPatch(lab,{[p.key]:v}))}/>)}</div>
      <div className="equation-box"><div><div className="field-label">Relationship</div><div className="formula">{lab.formula}</div></div><div className="output"><div className="field-label">{lab.result}</div><div className="value" id="result-value">{hide?'Make a prediction':<>{fmt(value)}<span className="unit">{lab.unit}</span></>}</div></div></div>
      <p className="live-text" id="live-text" role="status" aria-live="polite">{hide?'Predict the result and its direction before revealing the outcome.':dc&&!closed?'The switch is open: no current flows. Close it to restore the selected circuit.':liveSentence(lab,params)}</p><div className={'metric-strip'+(hide||!metrics.length?' hidden':'')} id="metrics">{!hide&&metrics.map(([label,n,u])=><div key={label} className="metric-item"><small>{label}</small><strong>{fmt(n)} <span className="helper">{u}</span></strong></div>)}</div>
    </section>
    {imageOpticsIds.has(lab.id)&&<OpticsImagePanel lab={lab} params={params} hide={hide}/>}
    <div className="graph-card"><div className="section-row"><h3>How does one variable change the result?</h3><label><span className="sr-only">Graph horizontal variable</span><select id="graph-variable" value={graphKey} onChange={e=>setGraphKey(e.target.value)}>{lab.params.map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label></div><Canvas id="graph" width={phone?420:840} height={270} label="Parameter response graph. Other values stay fixed." draw={graphDraw}/><div className="legend"><span>Current parameters</span><span className="baseline">Captured baseline</span></div><div className="section-row"><div><button id="capture" onClick={()=>setBaseline({...params})}>Capture baseline</button> <button id="clear-baseline" disabled={!baseline} onClick={()=>setBaseline(null)}>Clear</button></div><button id="reset" onClick={reset}>Reset values</button></div><p id="comparison" className="helper">{dc&&comparison?'Closed-circuit parameter comparison: ':''}{comparison}</p><p className="graph-caption">{dc?'This graph assumes a closed switch. ':''}All other values stay fixed. Extreme values near optical singularities are clipped; gaps indicate no finite solution. A parameter absent from this result produces a flat line.</p></div>
    <div className="split"><div className="card"><h3>What to notice</h3><p>{lab.explain}</p><details><summary className="helper">Show the current substitution</summary><div className="worked"><code id="substitution">{hide?'Reveal the outcome to see the numerical substitution.':dc&&!closed?'Open switch: I = 0 A. Close the circuit to apply the steady-current formula.':substitution(lab,params)}</code></div></details></div><div className="card assumption"><h3>Model assumptions</h3><p>{lab.assumptions}</p></div></div><details className="card"><summary>What this chapter’s models do not cover</summary><p>{chapter.limits}</p></details>
    {chapter.topic==='Optics'&&<div className="sandbox-invite card"><div><h3>See your picture through light</h3><p>Compare concave and convex lenses, mirrors and underwater refraction.</p></div><button className="primary" onClick={()=>routeTo('light')}>Open the optics image sandbox →</button></div>}
    {[22,23].includes(chapter.id)&&<div className="sandbox-invite card"><div><h3>Watch a capacitor store energy</h3><p>Follow charge, voltage and current through a charging or discharging circuit.</p></div><button className="primary" onClick={()=>routeTo('charge')}>Open the electricity sandbox →</button></div>}
    {chapter.id===3&&<div className="sandbox-invite card"><div><h3>Try gravity with your hands</h3><p>Lift a mass, let go, and follow its speed and energy.</p></div><button onClick={()=>routeTo('drop')} className="primary">Open the mass drop sandbox →</button></div>}
  </>;
}
export function DropSandbox(){
  const [height,setHeight]=useState(6),[mass,setMass]=useState(1),[gravity,setGravity]=useState(9.8),[x,setX]=useState(260),[running,setRunning]=useState(false),[time,setTime]=useClock(running),[held,setHeld]=useState(false),[released,setReleased]=useState(false);
  const svg=useRef(null),active=useRef(null),phone=usePhone();const fall=freeFall(height,gravity,time,mass),y=320-fall.height*26,barWidth=phone?430:255;
  useEffect(()=>{if(running&&fall.landed)setRunning(false)},[running,fall.landed]);
  function prepare(){setRunning(false);setTime(0);setReleased(false)}
  function release(){setHeld(false);setTime(0);setReleased(true);setRunning(true)}
  function position(e){const rect=svg.current.getBoundingClientRect();setX(clamp((e.clientX-rect.left)*(phone?530:840)/rect.width,90,450));setHeight(Number(clamp((320-(e.clientY-rect.top)*(phone?740:370)/rect.height)/26,.1,10).toFixed(2)))}
  const landing=released&&fall.landed;
  return <><h1>Lift it.<br/><em>Let gravity take over.</em></h1><p>Drag the mass up or down, then let go to drop it from rest. Change the mass or gravity and compare the fall.</p>
    <section className="lab-card"><header className="lab-header"><h3>Mass drop sandbox</h3><span className="status">{held?'HELD':landing?'LANDED':running?'FALLING':'READY'}</span></header>
      <div className="drop-stage"><svg id="drop-scene" ref={svg} viewBox={phone?'0 0 530 740':'0 0 840 370'} aria-label="Drag the mass vertically and release to drop it" onPointerMove={e=>{if(e.pointerId===active.current)position(e)}} onPointerUp={e=>{if(e.pointerId!==active.current)return;active.current=null;svg.current.releasePointerCapture?.(e.pointerId);release()}} onPointerCancel={e=>{if(e.pointerId!==active.current)return;active.current=null;setHeld(false);prepare()}}>
        <rect width={phone?530:840} height={phone?740:370} fill="#f2f7f4"/>{Array.from({length:11},(_,i)=><g key={i}><line x1="70" y1={320-i*26} x2="480" y2={320-i*26} stroke="#dce7df" strokeDasharray="3 5"/><text x="20" y={325-i*26} fill="#6b7e73" fontSize="12">{i} m</text></g>)}
        <line x1="65" y1="346" x2="480" y2="346" stroke="#173f37" strokeWidth="3"/><rect x="65" y="347" width="415" height="23" fill="#d5decf"/>
        <line x1={x} y1="55" x2={x} y2="320" stroke="#9fbbb0" strokeDasharray="5 5"/>
        <g data-testid="drop-mass" className="mass-handle" role="slider" tabIndex={0} aria-label="Mass release height. Arrow keys lift or lower; Enter drops." aria-valuemin={.1} aria-valuemax={10} aria-valuenow={height} aria-valuetext={`${height} metres; ${mass} kilograms`} onPointerDown={e=>{if(active.current!==null||(e.button!==undefined&&e.button!==0))return;e.preventDefault();prepare();active.current=e.pointerId;svg.current.setPointerCapture?.(e.pointerId);setHeld(true);position(e)}} onKeyDown={e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();prepare();setHeight(h=>clamp(h+(['ArrowUp','ArrowRight'].includes(e.key)?.25:-.25),.1,10))}else if(e.key==='Enter'||e.key===' '){e.preventDefault();release()}}}>
          <circle data-testid="mass-body" cx={x} cy={y} r="26" fill="#d5a155" stroke={held?'#173f37':'#a47334'} strokeWidth="3"/><circle cx={x} cy={y} r={phone?42:36} fill="transparent"/><text x={x} y={y+5} textAnchor="middle" fill="#173f37" fontSize="13" pointerEvents="none">{mass} kg</text>
        </g>
        <g data-testid="drop-energy-panel" className="energy-panel" transform={phone?'translate(-480 370)':undefined}><text x="525" y="65" fill="#117c72" fontSize="13">ENERGY IN MOTION</text><text x="525" y="105" fill="#173f37" fontSize="18">h = h₀ − ½gt²</text><text x="525" y="140" fill="#173f37" fontSize="18">v = gt</text><text x="525" y="185" fill="#506b6a" fontSize="14">Potential energy → kinetic energy</text>
        <rect x="525" y="215" width={barWidth} height="15" fill="#e0e8de"/><rect x="525" y="215" width={barWidth*fall.pe/(mass*gravity*height)} height="15" fill="#117c72"/><text x="525" y="250" fill="#117c72" fontSize="14">PE: {fmt(fall.pe)} J</text>
        <rect x="525" y="267" width={barWidth} height="15" fill="#e0e8de"/><rect x="525" y="267" width={barWidth*fall.ke/(mass*gravity*height)} height="15" fill="#d5a155"/><text x="525" y="302" fill="#946e35" fontSize="14">KE: {fmt(fall.ke)} J</text></g>
      </svg></div>
      <div className="canvas-toolbar"><button id="drop-release" className="primary" onClick={release}>Drop from {height.toFixed(2)} m ↓</button><button id="drop-pause" disabled={!released||landing} onClick={()=>setRunning(!running)}>{running?'Ⅱ Pause':'▶ Resume'}</button><button id="drop-reset" onClick={prepare}>↻ Reset</button><span className="helper" id="drop-time">t = {fall.time.toFixed(2)} s</span></div>
      <p className="drag-hint"><Icon name="move"/> Grab the mass and release it anywhere above the ground. Keyboard: ↑ / ↓ to lift, Enter to drop.</p>
      <div className="control-panel">{[{key:'height',label:'Release height',unit:'m',min:.1,max:10,step:.1},{key:'mass',label:'Mass',unit:'kg',min:.5,max:10,step:.5},{key:'gravity',label:'Gravity',unit:'m/s²',min:1,max:20,step:.1}].map(p=><Parameter key={p.key} param={p} value={p.key==='height'?height:p.key==='mass'?mass:gravity} onChange={v=>{prepare();const n=clamp(v,p.min,p.max);(p.key==='height'?setHeight:p.key==='mass'?setMass:setGravity)(n)}}/>)}</div>
      <div className="metric-strip"><div className="metric-item"><small>Height now</small><strong id="drop-height">{fmt(fall.height)} m</strong></div><div className="metric-item"><small>{landing?'Impact speed':'Downward speed'}</small><strong id="drop-speed">{fmt(fall.speed)} m/s</strong></div><div className="metric-item"><small>Potential energy</small><strong id="drop-pe">{fmt(fall.pe)} J</strong></div><div className="metric-item"><small>Kinetic energy{landing?' just before impact':''}</small><strong id="drop-ke">{fmt(fall.ke)} J</strong></div></div>
      <p className="live-text" id="drop-status" role="status">{landing?`Landed after ${fmt(fall.duration)} s. Impact speed ${fmt(fall.speed)} m/s. Reset or lift the mass for another drop.`:held?'Holding the mass. Release to drop from rest.':running?'Potential energy becomes kinetic energy as the mass falls.':'Ready to drop. Try the same height with a different mass.'}</p>
    </section><div className="split"><div className="card"><h3>Does a heavier mass fall faster?</h3><p>In this model, changing mass changes energy but does not change the fall time or acceleration. Change g to compare gravity on different worlds.</p></div><div className="card assumption"><h3>Model assumptions</h3><p>Constant gravity, release from rest, and no air resistance. The run stops at ground contact. Impact speed and kinetic energy report the instant before impact; bouncing and energy loss during impact are not modeled.</p></div></div><button onClick={()=>routeTo('chapter/3')}>← Back to kinematics</button>
  </>;
}
function Practice({chapter,lab,question,setQuestion,setParams,solved,markSolved}){
  const [answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(null),[choice,setChoice]=useState(null);let s=question.params;
  return <><div className="section-row"><h2>Put the idea to work</h2></div><LabTabs chapter={chapter} lab={lab} pane="practice"/>
    <section className="card question"><h3>{lab.challenge}</h3><p className="helper">Numerical practice · {lab.title}</p><div className="scenario">{lab.params.map(p=><span className="chip" key={p.key}>{p.label}: <strong>{s[p.key]}</strong> {p.unit}</span>)}</div><p className="helper">These question values are fixed. The formula is {lab.formula}.</p><form id="answer-form" onSubmit={e=>{e.preventDefault();const correct=checkAnswer(question.expected,answer);setFeedback(correct);if(correct)markSolved('lab:'+lab.id)}}><div className="answer-row"><label className="sr-only" htmlFor="answer">Your numerical answer</label><input id="answer" type="text" placeholder="Your answer" value={answer} onChange={e=>setAnswer(e.target.value)} autoComplete="off"/><span>{lab.unit||'dimensionless'}</span><button className="primary" type="submit">Check answer</button></div></form><p className="helper">Scientific notation is accepted. Nonzero answers use 1% relative tolerance. Special cases accept “infinity” or “TIR”.</p><div id="feedback" aria-live="polite">{feedback!==null&&<div className={'feedback'+(feedback?'':' wrong')}>{feedback?'✓ Correct. '+liveSentence(lab,s):'Check your unit conversion, signs and arithmetic. Try again, or open the hint and worked answer.'}</div>}</div><div className="section-row"><button id="new-question" onClick={()=>{setQuestion(makeQuestion(lab));setAnswer('');setFeedback(null)}}>New values ↻</button><button id="load-question" onClick={()=>{setParams(s);routeTo(labRoute(chapter,lab))}}>Explore these values →</button></div><details><summary>Hint</summary><p className="helper">Use {lab.formula}, and convert units before substituting. {lab.assumptions}</p></details><details id="worked"><summary>Reveal the worked answer</summary><div className="worked"><p>{lab.formula}</p><ul>{lab.params.map(p=><li key={p.key}>{p.label} = {s[p.key]} {p.unit}</li>)}</ul><code>{substitution(lab,s)}</code><p><strong>Answer: {fmt(question.expected)} {lab.unit}</strong></p><p>{liveSentence(lab,s)}</p></div></details><p className="session-note">{solved['lab:'+lab.id]?'✓ You have answered this practice type correctly.':'A correct answer adds this practice type to your progress.'}</p></section>
    <section className="card question"><h3>{chapter.quiz.prompt}</h3><p className="helper">Concept check</p><div className="quiz-options">{chapter.quiz.options.map((option,i)=><button key={i} data-quiz={i} className={choice===i?(i===chapter.quiz.answer?'correct':'wrong'):''} onClick={()=>{setChoice(i);if(i===chapter.quiz.answer)markSolved('quiz:'+chapter.id)}}>{String.fromCharCode(65+i)}. {option}</button>)}</div><div id="quiz-feedback" aria-live="polite">{choice!==null&&<div className={'feedback'+(choice===chapter.quiz.answer?'':' wrong')}>{choice===chapter.quiz.answer?'✓ Correct.':'Try again.'} {chapter.quiz.why}</div>}</div></section><div className="book-note">These are generated companion questions. For the uploaded book’s questions, open Textbook exercises.</div>
  </>;
}
function SourceUnavailable({chapter,error}){return <p className="helper">{error||'Loading source chapter…'} <a href={`source.pdf#page=${chapter.page+5}`} target="_blank" rel="noopener">Open original PDF ↗</a></p>}
function Reading({chapter,source,error}){
  const [filter,setFilter]=useState('');if(!source)return <SourceUnavailable chapter={chapter} error={error}/>;
  let paragraphs=source.text.split(/\n\s*\n/).filter(x=>x.trim());
  function sectionLink(section){setFilter('');let idx=paragraphs.findIndex(t=>t.includes(section.number)&&t.includes(section.title));requestAnimationFrame(()=>document.getElementById('source-p-'+idx)?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}))}
  const visible=paragraphs.map((t,i)=>({t,i})).filter(({t})=>t.toLowerCase().includes(filter.toLowerCase()));
  return <section className="source-reader"><div className="section-row"><h2>The source chapter</h2><a className="external" href={`source.pdf#page=${source.pdfPage}`} target="_blank" rel="noopener">Original pages ↗</a></div><div className="book-note">Text extracted from the uploaded CDC feedback copy. Figures are in the PDF; extraction can disrupt equations, tables and subscripts. Use the PDF for exact notation. Laboratories use separately implemented equations and state their assumptions.</div><label htmlFor="reader-search" className="helper">Find within this chapter</label><input id="reader-search" className="search" placeholder="Type a word or phrase…" type="search" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="source-list" style={{marginTop:20}}>{source.sections.map((s,i)=><button className="section-link" key={i} onClick={()=>sectionLink(s)}>{s.number} {s.title.slice(0,65)}</button>)}</div><div id="source-text">{visible.length?visible.map(({t,i})=><pre key={i} id={'source-p-'+i}>{t}</pre>):<p className="empty">No matching passages.</p>}</div><p className="source-figure-note">Source: Government of Nepal, Curriculum Development Centre. Physics Grade 11, first edition 2024, feedback copy.</p></section>;
}
function Notebook({chapter,source,error,saved,updateSaved}){
  const [filter,setFilter]=useState(''),[mode,setMode]=useState('all');if(!source)return <SourceUnavailable chapter={chapter} error={error}/>;
  const cards=source.questions.map((q,i)=>({...q,index:i,key:`${chapter.id}:${i}`})).filter(q=>q.text.toLowerCase().includes(filter.toLowerCase())&&(mode!=='answers'||q.printed.length)&&(mode!=='unreviewed'||!saved.sourceDone[q.key]));
  function exportNotes(){let lines=[`Physics 11 — Chapter ${chapter.id}: ${chapter.title}`,'','Personal study notes; source questions are not automatically graded.',''];source.questions.forEach((q,i)=>{let note=saved.notes[`${chapter.id}:${i}`];if(note)lines.push(`Question ${q.number}`,note,'')});let url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download=`physics11-chapter-${chapter.id}-notes.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <><div className="section-row"><h2>Your textbook notebook</h2><a href={`source.pdf#page=${source.pdfPage}`} target="_blank" rel="noopener">Source figures & keys ↗</a></div><div className="book-note">These cards contain extracted source questions. Check diagrams and broken equations in the PDF. Save your working, reveal printed answers where available, and mark your review. Printed excerpts are not independently verified or automatically graded.</div><div className="filter-row"><label className="sr-only" htmlFor="exercise-search">Search source questions</label><input id="exercise-search" type="search" placeholder="Search questions in this chapter…" value={filter} onChange={e=>setFilter(e.target.value)}/><label className="sr-only" htmlFor="exercise-filter">Filter questions</label><select id="exercise-filter" value={mode} onChange={e=>setMode(e.target.value)}><option value="all">All questions</option><option value="answers">With printed answers</option><option value="unreviewed">Not yet reviewed</option></select><button id="export-notes" onClick={exportNotes}>Export my notes ↓</button></div><div className="helper" id="question-count">{cards.length} of {source.questions.length} extracted cards shown. Source numbering is retained.</div><div id="source-questions">{cards.length?cards.map(q=><article className="source-question" key={q.key}><header><strong>Source question {q.number}</strong><button className={'self-check'+(saved.sourceDone[q.key]?' active':'')} data-review={q.index} aria-pressed={!!saved.sourceDone[q.key]} onClick={()=>updateSaved('sourceDone',q.key,!saved.sourceDone[q.key])}>{saved.sourceDone[q.key]?'✓ Reviewed':'Mark reviewed'}</button></header><div className="prompt">{q.text}</div><label htmlFor={'note-'+q.index}>Your working / explanation</label><textarea id={'note-'+q.index} data-note={q.index} placeholder="Show your reasoning. Notes are saved in this browser." value={saved.notes[q.key]||''} onChange={e=>updateSaved('notes',q.key,e.target.value)}/>{q.printed.length?<details><summary>Reveal the source’s printed answer excerpt</summary><div className="printed">{q.printed.join('\n\n')}</div><p className="helper">Check against the PDF and your reasoning.</p></details>:<p className="helper">No printed answer was extracted for this card. Use the PDF or ask a teacher to review your explanation.</p>}</article>):<p className="empty">No questions match this filter.</p>}</div></>;
}
function Chapter({chapter,lab,pane,source,error,saved,updateSaved}){
  const [params,setValues]=useState(()=>initial(lab)),[question,setQuestion]=useState(()=>makeQuestion(lab)),[baseline,setBaseline]=useState(null),[hide,setHide]=useState(false);
  const setParams=patch=>setValues(s=>({...s,...normalizedPatch(lab,patch)}));
  return <><header className="intro"><h1>{chapter.title}</h1><p>{chapter.intro}</p><div className="meta"><span>Chapter {String(chapter.id).padStart(2,'0')} · {chapter.topic}</span><span>Explore at your own pace</span><span>3 live experiments</span><span>Source pages {chapter.page}–{source?.lastPage??'…'}</span></div></header><nav className="tabs" aria-label="Chapter sections">{[['lab','Explore & learn'],['practice','Practice & feedback'],['read','Source reading'],['exercises','Textbook exercises']].map(([id,label])=><button key={id} className={'tab'+(pane===id?' selected':'')} data-pane={id} aria-current={pane===id?'page':undefined} onClick={()=>routeTo(labRoute(chapter,lab,id))}>{label}</button>)}</nav><div id="pane">
    {pane==='lab'&&<Lab {...{chapter,lab,params,setParams,baseline,setBaseline,hide,setHide}}/>}
    {pane==='practice'&&<Practice {...{chapter,lab,question,setQuestion,setParams}} solved={saved.solved} markSolved={key=>updateSaved('solved',key,true)}/>}
    {pane==='read'&&<Reading {...{chapter,source,error}}/>}
    {pane==='exercises'&&<Notebook {...{chapter,source,error,saved,updateSaved}}/>}
    </div><div className="chapter-footer"><button disabled={chapter.id===1} id="previous" onClick={()=>routeTo(`chapter/${chapter.id-1}`)}>← Previous chapter</button><button className={'mark-button'+(saved.read[chapter.id]?' complete':'')} id="mark-read" onClick={()=>updateSaved('read',chapter.id,!saved.read[chapter.id])}>{saved.read[chapter.id]?'✓ Reading complete':'Mark reading complete'}</button><button disabled={chapter.id===26} id="next" onClick={()=>routeTo(`chapter/${chapter.id+1}`)}>Next chapter →</button></div></>;
}
function Home({book,loading,saved}){const topics=[...new Set(chapters.map(c=>c.topic))];return <>
  <section className="home-hero"><div className="hero-copy"><h1>Don’t just read it.<br/><em>See it happen.</em></h1><p>Grab a vector. Pull a spring. Drop a mass. Change the physical world and watch the equations follow.</p><div className="hero-actions"><button className="primary" id="begin" onClick={()=>routeTo('chapter/3/projectile/lab')}>Explore projectile motion<Icon name="arrow"/></button><a href="#plan">See the chapter plan</a></div></div><div className="start-experiments"><h2>Try an experiment</h2><button id="begin-drop" onClick={()=>routeTo('drop')}><span><strong>Drop a mass</strong><small>Lift it. Release it. Follow its energy.</small></span><Icon name="arrow"/></button><button id="begin-light" onClick={()=>routeTo('light')}><span><strong>Shape the light</strong><small>See a picture through lenses and mirrors.</small></span><Icon name="arrow"/></button><button id="begin-charge" onClick={()=>routeTo('charge')}><span><strong>Follow the charge</strong><small>Watch a capacitor fill, then discharge.</small></span><Icon name="arrow"/></button><button onClick={()=>routeTo('chapter/2/vector/lab')}><span><strong>Drag a vector</strong><small>Change direction and magnitude by hand.</small></span><Icon name="arrow"/></button><button onClick={()=>routeTo('chapter/8/spring/lab')}><span><strong>Pull a spring</strong><small>Release the mass to start an oscillation.</small></span><Icon name="arrow"/></button></div></section>
  <p className="book-summary">NEB Grade 11 · <strong>26 chapters</strong> · 78 laboratories · 104 practice types · {loading?'Loading source exercises…':book.reduce((n,c)=>n+c.questions.length,0)+' source exercise cards'}</p>
  <div className="section-row catalog-heading"><h2>A whole world to explore</h2><a href="source.pdf" target="_blank" rel="noopener">Read the source textbook<Icon name="book"/></a></div>
  <div className="chapter-catalog">{topics.map(topic=><section className="catalog-group" key={topic}><h3>{topic}</h3><div className="chapter-grid">{chapters.filter(c=>c.topic===topic).map(c=><button className="chapter-tile" key={c.id} data-ch={c.id} onClick={()=>routeTo(`chapter/${c.id}`)}><span className="chapter-number">{String(c.id).padStart(2,'0')}</span><span className="chapter-description"><strong>{c.title}</strong><small>{c.labs.length} experiments · source p. {c.page}{saved.read[c.id]?' · ✓ read':''}</small></span><Icon name="arrow"/></button>)}</div></section>)}</div>
  <div className="split"><div className="card"><h3>Predict. Change. Understand.</h3><p>Drag the rings in supported diagrams, or use their sliders. Try prediction mode, capture a baseline, and compare two scenarios.</p></div><div className="card assumption"><h3>A companion to the source book</h3><p>Read the source chapters and exercises here, or open the PDF for diagrams and exact notation. Models explain their assumptions; written exercises use self-assessment.</p></div></div></>}
function Plan(){return <><h1>Every chapter.<br/><em>A way to explore it.</em></h1><div className="page-banner"><a href="plan.md" download>Download the full plan ↓</a></div><p className="plan-intro">26 chapters, each with three analytical laboratories, a live graph, practice and its source reading. The book is built with React components, Canvas 2D and Pretext text layout.</p><div className="book-note">Direct manipulation: vector tips, projectile launch velocity, spring mass, optical objects, incident rays, charge separation, torque lever, capacitor plate and flux normal. The mass drop sandbox demonstrates free fall and energy. The electricity sandbox shows capacitor charging and discharging; DC labs animate branch current and reverse electron drift. Other models use linked parameter controls.</div><div className="book-note">Source audit: Chapter 25 also contains semiconductors. Chapter 26 is titled “Solids” but contains particles and cosmology. Numbering is preserved.</div><div className="plan-table"><table><thead><tr><th>Chapter / page</th><th>Implemented interactions</th><th>What stays reading or practical</th></tr></thead><tbody>{chapters.map(c=><tr key={c.id}><td><a href={`#chapter/${c.id}`}>{c.id}. {c.title}</a><br/><span className="helper">Source p. {c.page}</span></td><td>{c.labs.map(l=><div className="lab-plan" key={l.id}><strong>{l.title}</strong><br/><span className="helper">{l.formula}{handlesFor(l,initial(l)).length?' · draggable diagram':''}</span></div>)}</td><td>{c.limits}</td></tr>)}</tbody></table></div><div className="split"><div className="card"><h3>Checked practice</h3><p>Numerical questions use frozen values, hints, worked substitutions and 1% tolerance. One conceptual multiple-choice check accompanies each chapter.</p></div><div className="card assumption"><h3>Source exercise notebook</h3><p>Questions accept saved working and self-assessment. Printed-answer excerpts are revealed where available. They are not independently verified or automatically graded.</p></div></div><div className="card"><h3>Implementation boundaries</h3><p>Analytical equations drive the models. Dragging updates their parameters; it does not turn every diagram into a rigid-body simulation. Real measurement, fracture, fluid flow, optical aberration and microscopic quantum dynamics remain reading or physical activities.</p></div></>}
export function App(){
  const [hash,setHash]=useState(location.hash),[saved,setSaved]=useState(readSaved),[search,setSearch]=useState(''),[menu,setMenu]=useState(false),[book,setBook]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[storageError,setStorageError]=useState(false),[mobile,setMobile]=useState(()=>matchMedia('(max-width: 1024px)').matches);
  useEffect(()=>{const query=matchMedia('(max-width: 1024px)'),update=()=>setMobile(query.matches);query.addEventListener?.('change',update);return ()=>query.removeEventListener?.('change',update)},[]);
  useEffect(()=>{if(!mobile||!menu)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=document.querySelector('.nav-close');close?.focus();function trap(e){if(e.key!=='Tab')return;const items=[...document.querySelectorAll('#sidebar button:not([disabled]),#sidebar a,#sidebar input')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}window.addEventListener('keydown',trap);return ()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',trap);document.getElementById('menu')?.focus()}},[mobile,menu]);
  useEffect(()=>{const onHash=()=>{setHash(location.hash);setMenu(false);window.scrollTo?.({top:0,behavior:'instant'})},escape=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('hashchange',onHash);window.addEventListener('keydown',escape);return ()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('keydown',escape)}},[]);
  useEffect(()=>{let canceled=false;fetch('book.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!canceled)setBook(data)}).catch(()=>{if(!canceled)setError('The source text could not be loaded. The laboratories still work.')}).finally(()=>{if(!canceled)setLoading(false)});return ()=>{canceled=true}},[]);
  useEffect(()=>{try{localStorage.setItem('physics11-progress-v1',JSON.stringify(saved))}catch{setStorageError(true)}},[saved]);
  const updateSaved=(section,key,value)=>setSaved(s=>({...s,[section]:{...s[section],[key]:value}}));
  const parts=hash.replace(/^#/,'').split('/'),chapter=parts[0]==='chapter'?chapters.find(c=>c.id===Number(parts[1])):null,lab=chapter?(chapter.labs.find(l=>l.id===parts[2])||chapter.labs[0]):null,pane=['lab','practice','read','exercises'].includes(parts[3])?parts[3]:'lab',progress=Math.round(Object.keys(saved.solved).length/104*100);
  const visibleChapters=chapters.filter(c=>(c.title+' '+c.topic+' '+c.labs.map(l=>l.title).join(' ')).toLowerCase().includes(search.toLowerCase()));
  let group='';
  return <><a className="skip-link" href="#content" onClick={e=>{e.preventDefault();document.getElementById('content')?.focus()}}>Skip to content</a><div className="shell">{menu&&<button className="nav-backdrop" aria-label="Close chapter navigation" onClick={()=>setMenu(false)}/>}<aside className={'sidebar'+(menu?' open':'')} id="sidebar" inert={mobile&&!menu} role={mobile?'dialog':undefined} aria-modal={mobile&&menu?true:undefined} aria-hidden={mobile&&!menu?true:undefined} aria-label="Chapter navigation"><button className="nav-close" aria-label="Close chapter navigation" onClick={()=>setMenu(false)}>Close</button><a href="#home" className="brand"><span className="brand-mark">φ</span><div><strong>Physics 11</strong><small>THE LIVING BOOK</small></div></a><label className="sr-only" htmlFor="search">Search chapters and laboratories</label><input id="search" className="search" placeholder="Search the book…" value={search} onChange={e=>setSearch(e.target.value)} type="search"/><div className="side-top"><button onClick={()=>routeTo('home')}>Contents</button><button onClick={()=>routeTo('plan')}>Chapter plan</button></div><button className={'sandbox-nav'+(parts[0]==='drop'?' active':'')} onClick={()=>routeTo('drop')}><Icon name="move"/>Mass drop sandbox</button><button className={'sandbox-nav'+(parts[0]==='charge'?' active':'')} onClick={()=>routeTo('charge')}><Icon name="play"/>Electricity sandbox</button><button className={'sandbox-nav'+(parts[0]==='light'?' active':'')} onClick={()=>routeTo('light')}><Icon name="book"/>Optics image sandbox</button><nav id="chapters" className="chapters" aria-label="Book chapters">{visibleChapters.map(c=>{const show=c.topic!==group;group=c.topic;return <React.Fragment key={c.id}>{show&&<div className="group-label">{c.topic}</div>}<button className={'chapter-link'+(chapter?.id===c.id?' selected':'')} data-ch={c.id} aria-current={chapter?.id===c.id?'page':undefined} onClick={()=>routeTo(`chapter/${c.id}`)}><span className="n">{String(c.id).padStart(2,'0')}</span><span>{c.title}</span>{saved.read[c.id]&&<span className="done-dot" title="Reading marked complete">✓</span>}</button></React.Fragment>})}{!visibleChapters.length&&<p className="nav-empty" role="status">No chapters match. Try “motion” or “heat”.</p>}</nav><div className="side-foot"><div><span id="progress-number">{progress}%</span> checked practice completed</div><div className="progress-track"><span id="progress-bar" style={{width:progress+'%'}}/></div>NEB · Grade 11 · CDC Nepal<br/>Progress and notes stay in this browser.</div></aside>
    <main className="main" inert={mobile&&menu}><header className="topbar"><div className="breadcrumb"><button className="menu" id="menu" aria-label="Open chapter navigation" aria-expanded={menu} aria-controls="sidebar" onClick={()=>setMenu(!menu)}><Icon name="menu"/></button><a href="#home">The living book</a><span>/</span><span>{chapter?.topic||'An interactive physics companion'}</span></div><a href={`source.pdf${chapter?'#page='+(chapter.page+5):''}`} target="_blank" rel="noopener" className="external">Source textbook ↗</a></header>{storageError&&<div className="storage-warning">Browser storage is unavailable. Progress and notes are temporary.</div>}<div className="content" id="content" tabIndex={-1}>
      {chapter?<Chapter key={lab.id} {...{chapter,lab,pane,saved,updateSaved,error}} source={book.find(c=>c.id===chapter.id)}/>:parts[0]==='plan'?<Plan/>:parts[0]==='drop'?<DropSandbox/>:parts[0]==='light'?<OpticsSandbox Parameter={Parameter}/>:parts[0]==='charge'?<ElectricitySandbox Parameter={Parameter} useClock={useClock} Icon={Icon}/>:<Home {...{book,loading,saved}}/>}
    </div></main></div></>;
}
createRoot(document.getElementById('app')).render(<App/>);
