// All controls are expressed in the displayed units; conversions occur in the model.
export const G=6.67430e-11, K=8.9875517923e9, EPS=8.8541878128e-12, R=8.314462618, C0=299792458;
const rad=x=>x*Math.PI/180, deg=x=>x*180/Math.PI;
const sinD=x=>x%180===0?0:Math.sin(rad(x)), cosD=x=>Math.abs(x%180)===90?0:Math.cos(rad(x));
export const p=(key,label,unit,min,max,step,value)=>({key,label,unit,min,max,step,value});
const L=(id,title,kind,formula,result,unit,params,compute,explain,assumptions,challenge)=>({id,title,kind,formula,result,unit,params,compute,explain,assumptions,challenge});
const Ch=(id,title,topic,page,intro,limits,labs,quiz)=>({id,title,topic,page,intro,limits,labs,quiz});
const q=(prompt,options,answer,why)=>({prompt,options,answer,why});
export const chapters=[
Ch(1,'Physical quantities','Foundations',1,'A measurement combines a number, a unit, and a level of confidence. Changing units changes the numerical value without changing the physical quantity. Dimensions test whether an equation could describe nature; they cannot establish that it is correct.','Definitions and measurement history stay as reading. Dimensional consistency does not determine numerical constants. Real instrument calibration requires a physical instrument.',[
L('units','Speed and units','measure','v (m/s) = v (km/h) ÷ 3.6','Speed','m/s',[p('v','Speed','km/h',0,180,1,72)],s=>s.v/3.6,'One kilometre is 1000 metres and one hour is 3600 seconds. Watch the same speed acquire two numerical descriptions.','Exact unit conversion; displayed readings are rounded.','Convert the chosen speed into metres per second.'),
L('uncertainty','Area and uncertainty','area','A = lb; ΔA ≈ bΔl + lΔb','Area','m²',[p('l','Length','m',1,150,1,110),p('b','Breadth','m',1,150,1,100),p('dl','Length uncertainty','m',0,5,.1,2),p('db','Breadth uncertainty','m',0,5,.1,4)],s=>s.l*s.b,'The first-order worst-case absolute area uncertainty is bΔl + lΔb. It grows when either measurement becomes less certain. This is a bound, not a standard deviation.','Small relative uncertainties; products of uncertainties are neglected.','Calculate the nominal area. Then compare it with the uncertainty shown.'),
L('dimensions','Build a dimension','dimensions','[Q] = Mᵃ Lᵇ Tᶜ','Time exponent','',[p('a','Mass exponent','',-3,3,1,1),p('b','Length exponent','',-3,3,1,1),p('c','Time exponent','',-3,3,1,-2)],s=>s.c,'Force has dimensions M¹L¹T⁻². Energy has M¹L²T⁻²; momentum has M¹L¹T⁻¹. Exponents combine algebraically when quantities are multiplied.','Only mass, length and time are represented here.','Read the time exponent from the dimension you constructed.')],q('Which quantity is dimensionless?',['Force','Strain','Energy','Speed'],1,'Strain is extension divided by original length: metres cancel.')),
Ch(2,'Vectors','Foundations',21,'A vector carries direction as well as magnitude. Its components describe the same vector along chosen axes. Add vectors component by component, and use a dot product to measure how strongly two vectors align.','Vector definitions and proofs remain readable. The lab uses a two-dimensional coordinate plane; three-dimensional generalization is described by the same component rules.',[
L('vector','Vector addition','vectors','R = √(A² + B² + 2AB cos θ)','Resultant magnitude','N',[p('a','Vector A','N',0,20,.5,8),p('b','Vector B','N',0,20,.5,6),p('theta','Angle between','°',0,180,1,90)],s=>Math.sqrt(Math.max(0,s.a*s.a+s.b*s.b+2*s.a*s.b*cosD(s.theta))),'At 0° the vectors reinforce; at 180° they oppose. At 90° the resultant is the hypotenuse of a right triangle.','A lies on the positive x axis; B is measured anticlockwise from A.','Find the magnitude of the resultant.'),
L('components','Resolve a vector','components','Aₓ = A cos θ; Aᵧ = A sin θ','Horizontal component','N',[p('a','Magnitude','N',0,30,.5,10),p('theta','Direction','°',-180,180,1,30)],s=>s.a*cosD(s.theta),'The horizontal and vertical projections change as you rotate the vector. Their squared sum remains A². Negative components point opposite the positive axes.','Angles are measured anticlockwise from +x.','Calculate the horizontal component, including its sign.'),
L('dot','Dot product','vectors','A · B = AB cos θ','Dot product','N²',[p('a','Vector A','N',0,20,.5,8),p('b','Vector B','N',0,20,.5,6),p('theta','Angle between','°',0,180,1,60)],s=>s.a*s.b*cosD(s.theta),'The dot product is zero for perpendicular vectors and negative when the angle exceeds 90°. It is a scalar, not a new arrow.','Both sample vectors are forces, so their product has units N².','Calculate the dot product.')],q('Two equal opposite vectors have a resultant of',['Twice either magnitude','Zero','One vector magnitude','An undefined magnitude'],1,'Their components cancel exactly.')),
Ch(3,'Kinematics','Mechanics',41,'Kinematics describes motion without explaining its cause. The slope of displacement against time is velocity; the slope of velocity against time is acceleration. In a projectile, horizontal and vertical motions share one clock.','The constant-acceleration and projectile models do not describe air resistance. Timing a real moving object remains a hands-on task.',[
L('motion','Constant acceleration','motion','s = ut + ½at²; v = u + at','Displacement','m',[p('u','Initial velocity','m/s',-10,30,1,5),p('a','Acceleration','m/s²',-5,10,.5,2),p('t','Elapsed time','s',0,10,.1,4)],s=>s.u*s.t+.5*s.a*s.t*s.t,'Velocity changes at a constant rate. The area under the velocity–time curve gives the displacement, including negative areas when motion reverses.','Acceleration is constant; position starts at zero.','Find displacement at the specified time.'),
L('projectile','Projectile laboratory','projectile','Range = u² sin(2θ) / g','Horizontal range','m',[p('u','Launch speed','m/s',1,50,1,20),p('theta','Launch angle','°',1,89,1,45),p('g','Gravity','m/s²',1,20,.1,9.8)],s=>s.u*s.u*Math.sin(2*rad(s.theta))/s.g,'Gravity bends the path downward while horizontal speed stays constant. Complementary launch angles have the same range when launch and landing heights are equal.','No drag; level ground; uniform g. The animation follows physical time.','Predict the horizontal range before revealing the trajectory.'),
L('relative','Relative velocity','relative','v relative = v₁ − v₂','Relative velocity','m/s',[p('v1','Object 1 velocity','m/s',-30,30,1,15),p('v2','Observer velocity','m/s',-30,30,1,5)],s=>s.v1-s.v2,'An observer moving alongside an object at the same velocity sees it at rest. Opposite signed velocities increase the relative speed.','One-dimensional motion in inertial frames.','Find object 1’s velocity measured by the observer.')],q('At the highest point of a projectile, its vertical acceleration is',['Zero','g downward','g upward','Horizontal'],1,'Vertical velocity is zero there, but gravity is still acting.')),
Ch(4,'Dynamics','Mechanics',73,'Forces change momentum. Newton’s second law relates net force to acceleration, while equilibrium requires both zero net force and zero net torque. Friction can prevent motion before any sliding begins.','Newton’s laws and conservation arguments need reasoning. The incline model distinguishes static and kinetic friction; real surfaces may not follow constant coefficients.',[
L('newton','Newton’s second law','force','a = F net / m','Acceleration','m/s²',[p('f','Net force','N',-40,40,1,12),p('m','Mass','kg',.5,10,.5,3)],s=>s.f/s.m,'For the same mass, doubling net force doubles acceleration. For the same force, doubling mass halves acceleration. Net force includes every force, with signs.','Constant mass, inertial frame, non-relativistic motion.','Calculate acceleration from the net force.'),
L('incline','Friction on a slope','incline','a = 0 if tan θ ≤ μₛ; otherwise g(sin θ − μₖ cos θ)','Downhill acceleration','m/s²',[p('theta','Slope angle','°',0,75,1,20),p('mus','Static coefficient','',0,1,.01,.4),p('ratio','Kinetic/static ratio','',0,1,.05,.75),p('m','Mass','kg',1,10,1,3)],s=>Math.tan(rad(s.theta))<=s.mus?0:9.8*(sinD(s.theta)-s.mus*s.ratio*cosD(s.theta)),'Static friction adjusts up to μₛN. Once the downhill component exceeds that limit, the block slides with kinetic friction μₖN. Here μₖ is a fraction of μₛ.','Block starts at rest; g = 9.8 m/s²; constant friction coefficients.','Determine whether the block moves, then calculate its acceleration.'),
L('torque','Turning effect','torque','τ = rF sin θ','Torque','N·m',[p('r','Lever arm','m',.1,3,.1,1),p('f','Force','N',0,50,1,20),p('theta','Angle to lever','°',0,180,1,90)],s=>s.r*s.f*sinD(s.theta),'Only the force component perpendicular to the lever turns it. A force along the lever produces no torque about the pivot.','Rigid lever; angle is between r and F.','Calculate the magnitude of torque about the pivot.')],q('A body moves with constant velocity. Its net force is',['Along its velocity','Zero','Opposite its velocity','Equal to its weight'],1,'Constant velocity means zero acceleration, so the net force is zero.')),
Ch(5,'Work, energy & power','Mechanics',103,'Work transfers energy when a force acts through displacement. Kinetic energy depends on speed squared; power measures how quickly energy is transferred. In a collision, momentum conservation does not always imply kinetic-energy conservation.','Energy bookkeeping and derivations remain reading. A sticking collision is one limiting model, not a universal collision rule.',[
L('work','Work at an angle','work','W = Fs cos θ','Work','J',[p('f','Force','N',0,100,1,20),p('s','Displacement','m',0,20,.5,5),p('theta','Force angle','°',0,180,1,30)],s=>s.f*s.s*cosD(s.theta),'Work is positive when force helps the displacement, zero when perpendicular, and negative when force opposes motion.','Constant force; straight displacement.','Calculate the work done by this force.'),
L('energy','Energy and power','energy','Eₖ = ½mv²; P average = Eₖ / t','Kinetic energy','J',[p('m','Mass','kg',.5,10,.5,2),p('v','Speed','m/s',0,20,.5,6),p('t','Acceleration time','s',.5,10,.5,3)],s=>.5*s.m*s.v*s.v,'Doubling speed quadruples kinetic energy. If this energy is supplied from rest over t seconds, Eₖ/t is the average power, without losses.','Non-relativistic motion; starts from rest; no losses.','Find the final kinetic energy.'),
L('collision','A sticking collision','collision','v final = (m₁u₁ + m₂u₂) / (m₁ + m₂)','Final velocity','m/s',[p('m1','Mass 1','kg',1,10,1,2),p('m2','Mass 2','kg',1,10,1,3),p('u1','Velocity 1','m/s',-10,10,1,6),p('u2','Velocity 2','m/s',-10,10,1,0)],s=>(s.m1*s.u1+s.m2*s.u2)/(s.m1+s.m2),'The joined bodies share one final velocity. Momentum is conserved for the isolated system; some kinetic energy becomes internal energy.','Perfectly inelastic collision; negligible external impulse.','Use momentum conservation to find the shared final velocity.')],q('If speed doubles, kinetic energy becomes',['Twice as large','Four times as large','Half as large','Unchanged'],1,'Kinetic energy is proportional to v².')),
Ch(6,'Circular motion','Mechanics',132,'Constant speed around a circle still requires acceleration because the velocity direction changes. The net inward force provides this acceleration; it is not an extra force to add to the force diagram.','Real banked turns can involve friction. Vertical-circle minimum-speed conditions require contact constraints beyond the uniform-circle model.',[
L('circle','Centripetal force','circle','F = mv² / r','Inward force','N',[p('m','Mass','kg',.5,10,.5,2),p('v','Speed','m/s',.5,20,.5,5),p('r','Radius','m',.5,10,.5,2)],s=>s.m*s.v*s.v/s.r,'Velocity points tangent to the circle; acceleration points toward the centre. Doubling speed requires four times the inward force at fixed radius.','Uniform circular motion. No outward force is added in an inertial frame.','Calculate the required inward force.'),
L('angular','Angular and linear speed','circle','v = ωr; T = 2π / ω','Linear speed','m/s',[p('omega','Angular speed','rad/s',.1,10,.1,2),p('r','Radius','m',.5,10,.5,3)],s=>s.omega*s.r,'All points of a rotating rigid disc share angular speed, but points farther from its centre have greater linear speed.','Uniform rotation; angular speed in radians per second.','Find the tangential speed.'),
L('bank','A frictionless banked road','incline','v = √(rg tan θ)','Design speed','m/s',[p('r','Turn radius','m',5,200,5,50),p('theta','Bank angle','°',0,60,1,15)],s=>Math.sqrt(s.r*9.8*Math.tan(rad(s.theta))),'The horizontal component of the normal force supplies the inward force. Only one speed needs no friction for a given radius and bank angle.','No friction; g = 9.8 m/s².','Calculate the speed requiring no friction.')],q('In uniform circular motion, velocity points',['Inward','Outward','Along the tangent','Nowhere'],2,'The instantaneous direction of motion is tangent to the circle.')),
Ch(7,'Gravitation','Mechanics',154,'Every mass attracts every other mass. Gravity weakens with the square of centre-to-centre distance. Satellites are continuously falling around Earth, with enough sideways speed to avoid reaching the surface.','GPS, geostationary geometry and historical discussion stay as guided reading. Orbits assume a spherical Earth; the orbit animation compresses the time scale.',[
L('gravity','Inverse-square attraction','gravity','F = Gm₁m₂ / r²','Attractive force','N',[p('m1','Mass 1','kg',1,100,1,10),p('m2','Mass 2','kg',1,100,1,20),p('r','Centre distance','m',1,20,.5,2)],s=>G*s.m1*s.m2/(s.r*s.r),'Doubling the distance reduces attraction to one quarter. The forces on the two bodies are equal in magnitude even when their masses differ.','Point masses, or non-overlapping spherical masses.','Calculate the gravitational attraction.'),
L('orbit','A circular Earth orbit','orbit','v = √(GM / (R Earth + h))','Orbital speed','m/s',[p('h','Altitude','km',0,40000,100,400)],s=>Math.sqrt(G*5.972e24/(6.371e6+s.h*1000)),'A higher circular orbit has a lower speed and a longer period. Orbital height is measured above Earth’s surface; distance in the equation is measured from its centre.','M Earth = 5.972 × 10²⁴ kg; R Earth = 6371 km; no atmosphere.','Calculate the circular orbital speed.'),
L('escape','Escape speed','orbit','v escape = √(2GM / r)','Escape speed','m/s',[p('h','Altitude','km',0,40000,100,0)],s=>Math.sqrt(2*G*5.972e24/(6.371e6+s.h*1000)),'Escape speed is √2 times circular orbital speed at the same radius. It is the initial speed needed to reach infinitely far away with zero remaining speed.','No atmosphere, further thrust, Earth rotation, or other gravitating bodies.','Find the local escape speed.')],q('If distance between two masses doubles, gravitational force becomes',['Four times','Twice','One half','One quarter'],3,'The inverse-square factor is 1/2².')),
Ch(8,'Elasticity','Mechanics',184,'Within its elastic range, a material returns to its original shape after the load is removed. Stress measures force per area; strain measures relative deformation. Young’s modulus describes the proportionality between them.','Plastic deformation, hysteresis and fracture require material data. The spring and wire are linear elastic models, not predictions of breaking strength.',[
L('spring','Hooke’s law','spring','F = kx; E = ½kx²','Restoring force magnitude','N',[p('k','Spring constant','N/m',10,500,10,100),p('x','Extension','m',0,.5,.01,.2),p('m','Oscillating mass','kg',.5,5,.5,1)],s=>s.k*s.x,'A spring exerts force opposite its extension. Stored energy grows with extension squared. The animation shows ideal oscillation around equilibrium with amplitude x.','Linear elastic range; no damping; ω = √(k/m).','Find the restoring-force magnitude at maximum extension.'),
L('young','Stretch a wire','wire','ΔL = FL / (AY)','Extension','mm',[p('f','Tension','N',0,1000,10,100),p('l','Original length','m',.5,5,.1,2),p('a','Cross-section','mm²',.1,10,.1,1),p('y','Young’s modulus','GPa',10,250,10,200)],s=>s.f*s.l/(s.a*1e-6*s.y*1e9)*1000,'Longer wires extend more under the same load. Increasing cross-sectional area or Young’s modulus reduces extension. The drawing exaggerates the extension.','Uniform wire; small strain; constant modulus.','Calculate extension in millimetres.'),
L('stress','Stress and strain','wire','σ = F/A; ε = σ/Y','Tensile stress','MPa',[p('f','Tension','N',0,1000,10,100),p('a','Cross-section','mm²',.1,10,.1,1),p('y','Young’s modulus','GPa',10,250,10,200)],s=>s.f/s.a,'Stress depends on force and area, while strain additionally depends on the material modulus. One newton per square millimetre is one megapascal.','Uniaxial load; linear response before yield.','Find the tensile stress in MPa.')],q('Hooke’s law applies',['To every deformation','Within the proportional elastic range','Only after fracture','Only to liquids'],1,'Force is proportional to extension only over the material’s proportional range.')),
Ch(9,'Heat and temperature','Thermal physics',208,'Temperature describes thermal state; heat is energy transferred because of a temperature difference. Thermal equilibrium means no net heat transfer. Kelvin has the same interval size as Celsius but a different zero.','Temperature is not a measure of total thermal energy. The thermometer is a scale illustration; it does not replace real thermometry.',[
L('temperature','Three temperature scales','thermometer','K = °C + 273.15; °F = 1.8°C + 32','Absolute temperature','K',[p('c','Celsius temperature','°C',-273.15,300,.01,25)],s=>s.c+273.15,'A Celsius rise of one degree is a Kelvin rise of one kelvin. Absolute zero is 0 K, corresponding to −273.15 °C.','Equilibrium thermodynamic temperature.','Convert this temperature to kelvin.'),
L('fahrenheit','Fahrenheit conversion','thermometer','°C = (°F − 32) × 5/9','Celsius temperature','°C',[p('f','Fahrenheit temperature','°F',-459.67,572,.01,98.6)],s=>(s.f-32)*5/9,'The Celsius and Fahrenheit intervals differ. The offset must be removed before scaling the interval.','Temperature is at or above absolute zero.','Convert the Fahrenheit reading to Celsius.'),
L('equilibrium','Thermal equilibrium','mixing','T final = (C₁T₁ + C₂T₂) / (C₁ + C₂)','Equilibrium temperature','°C',[p('t1','Body 1 temperature','°C',0,100,1,80),p('t2','Body 2 temperature','°C',0,100,1,20),p('c1','Body 1 heat capacity','J/K',100,1000,50,500),p('c2','Body 2 heat capacity','J/K',100,1000,50,500)],s=>(s.c1*s.t1+s.c2*s.t2)/(s.c1+s.c2),'The final temperature lies between the starting temperatures. The body with the larger heat capacity has a greater influence on the final value.','Isolated pair; constant heat capacities; no phase change.','Find their final common temperature.')],q('Heat is',['Temperature stored in a body','Energy transferred due to temperature difference','Measured in kelvin','Always proportional to mass alone'],1,'Heat describes an energy transfer, measured in joules.')),
Ch(10,'Thermal expansion','Thermal physics',222,'Heating usually increases dimensions as particles explore larger average separations. Linear, area and volume expansions refer to different geometries. Constraining an expanding solid creates stress instead of free expansion.','Pullinger’s apparatus and balanced-column experiments remain practical activities. First-order expansion neglects higher powers of the small fractional change.',[
L('expansion','Linear expansion','expansion','ΔL = αL₀ΔT','Length increase','mm',[p('l','Original length','m',.1,5,.1,1),p('alpha','Linear coefficient','×10⁻⁶/K',1,30,1,12),p('dt','Temperature rise','K',0,200,1,100)],s=>s.alpha*1e-6*s.l*s.dt*1000,'A longer rod or a larger temperature rise gives more expansion. The gap in the drawing is magnified so a millimetre-scale change can be seen.','Constant coefficient; unconstrained homogeneous rod.','Find the increase in length in millimetres.'),
L('volume','Volume expansion','expansion','ΔV ≈ 3αV₀ΔT','Volume increase','cm³',[p('v','Original volume','cm³',10,1000,10,100),p('alpha','Linear coefficient','×10⁻⁶/K',1,30,1,12),p('dt','Temperature rise','K',0,200,1,100)],s=>3*s.alpha*1e-6*s.v*s.dt,'For isotropic solids and small expansion, the volume coefficient is approximately three times the linear coefficient. A hole in a plate expands too.','Isotropic solid; αΔT ≪ 1.','Calculate the volume increase.'),
L('thermalstress','A constrained rod','wire','σ = YαΔT','Compressive stress','MPa',[p('y','Young’s modulus','GPa',10,250,10,200),p('alpha','Linear coefficient','×10⁻⁶/K',1,30,1,12),p('dt','Temperature rise','K',0,100,1,50)],s=>s.y*s.alpha*s.dt*.001,'Supports prevent the length increase that would occur freely. The resulting compressive stress can be large even for a modest temperature rise.','Perfectly fixed ends; linear elasticity; no buckling or yielding.','Calculate the compressive stress magnitude.')],q('For a small isotropic expansion, the volume coefficient is approximately',['α','2α','3α','α/3'],2,'Each of three dimensions contributes a first-order αΔT change.')),
Ch(11,'Quantity of heat','Thermal physics',246,'Heat can raise temperature or change phase. A substance at its melting point can absorb energy while its temperature stays fixed. Calorimetry equates energy lost by hotter bodies with energy gained by colder ones.','Real evaporation, pressure-dependent phase diagrams and calorimeter calibration need experimental data. Phase-change labs use water at standard pressure.',[
L('heat','Heating a substance','heat','Q = mcΔT','Heat supplied','J',[p('m','Mass','kg',.1,5,.1,1),p('c','Specific heat','J/(kg·K)',100,4200,100,4200),p('dt','Temperature rise','K',0,80,1,20)],s=>s.m*s.c*s.dt,'A larger specific heat means more energy is needed for the same temperature rise. Heat capacity is mc, while specific heat is a material property.','Constant specific heat; no phase change or losses.','Calculate the heat required.'),
L('latent','Melting ice','phase','Q = mL fusion','Heat for complete melting','J',[p('m','Ice mass','kg',.1,5,.1,1),p('fraction','Melted fraction','',0,1,.01,.5)],s=>s.m*334000,'Ice at 0 °C takes 334 kJ per kilogram to melt at standard pressure. The energy already absorbed is the melted fraction times this total; temperature remains 0 °C while both phases coexist.','Ice starts at 0 °C; L fusion = 334000 J/kg; no losses.','Find the total heat required to melt all the ice.'),
L('cooling','Newton’s law of cooling','cooling','T(t) = T ambient + (T₀ − T ambient)e⁻ᵏᵗ','Temperature after cooling','°C',[p('t0','Initial temperature','°C',20,100,1,80),p('ta','Ambient temperature','°C',0,40,1,20),p('k','Cooling constant','1/min',.01,.3,.01,.1),p('t','Elapsed time','min',0,60,1,10)],s=>s.ta+(s.t0-s.ta)*Math.exp(-s.k*s.t),'The temperature difference decreases exponentially. Cooling is faster at first because the temperature difference is larger; a colder initial body would warm toward ambient.','Uniform body temperature; constant ambient and effective cooling coefficient.','Find the temperature at the selected time.')],q('During melting of pure ice at constant pressure, temperature',['Continuously increases','Stays fixed while phases coexist','Drops to absolute zero','Depends only on the ice mass'],1,'Supplied energy changes phase rather than raising temperature.')),
Ch(12,'Rate of heat flow','Thermal physics',270,'Heat flows through conduction, convection and radiation. A temperature gradient drives conduction. Thermal radiation grows very strongly with absolute temperature, making kelvin essential in the fourth-power law.','Convection is illustrated rather than solved as a fluid simulation. Searle’s apparatus requires real measurement. Radiation models assume a grey surface with constant emissivity.',[
L('conduction','Heat through a wall','conduction','P = kAΔT / L','Heat flow rate','W',[p('k','Conductivity','W/(m·K)',.1,10,.1,1),p('a','Area','m²',.1,10,.1,2),p('dt','Temperature difference','K',0,100,1,20),p('l','Wall thickness','m',.05,1,.05,.2)],s=>s.k*s.a*s.dt/s.l,'A thicker wall reduces conduction; greater area, conductivity or temperature difference increases it. The model is steady state and one-dimensional.','Uniform wall; fixed face temperatures; no contact resistance.','Calculate the steady heat flow rate.'),
L('radiation','Net thermal radiation','radiation','P = εσA(T⁴ − T surroundings⁴)','Net outward power','W',[p('e','Emissivity','',.05,1,.05,.8),p('a','Surface area','m²',.1,5,.1,1),p('t','Surface temperature','K',100,1500,10,500),p('ta','Surroundings temperature','K',100,600,10,300)],s=>s.e*5.670374419e-8*s.a*(s.t**4-s.ta**4),'Net radiation is zero at equal temperatures. A negative result means the surface gains energy from hotter surroundings. Doubling absolute temperature greatly increases emission.','Grey body viewing a large uniform surrounding enclosure.','Calculate the signed net outward radiated power.'),
L('wien','Blackbody peak','spectrum','λ peak = b / T','Peak wavelength','μm',[p('t','Blackbody temperature','K',300,10000,100,5800)],s=>2897.771955/s.t,'Hotter blackbodies peak at shorter wavelengths. The plotted spectrum shows a relative wavelength distribution rather than total emitted power.','Ideal blackbody; b = 2.897771955 × 10⁻³ m·K.','Calculate the peak wavelength in micrometres.')],q('In Stefan’s law, temperature must be measured in',['Celsius','Fahrenheit','Kelvin','Any scale'],2,'The fourth-power law uses absolute temperature.')),
Ch(13,'Ideal gas','Thermal physics',289,'Pressure comes from momentum transfer when molecules hit container walls. The ideal-gas equation links pressure, volume, temperature and amount. Temperature controls the average translational kinetic energy, not the speed of every individual molecule.','Particles are a qualitative display, not a molecular dynamics calculation. Real gases deviate at high density and near condensation.',[
L('gas','Pressure, volume, temperature','gas','P = nRT / V','Gas pressure','kPa',[p('n','Amount','mol',.1,2,.1,1),p('t','Temperature','K',100,1000,10,300),p('v','Volume','L',1,50,1,20)],s=>s.n*R*s.t/s.v,'Compressing the gas at fixed temperature increases pressure. Heating it at fixed volume also raises pressure. The particles illustrate the kinetic interpretation.','Ideal gas; R = 8.314462618 J/(mol·K); absolute temperature.','Calculate pressure in kilopascals.'),
L('rms','Molecular speed','gas','v rms = √(3RT / M)','RMS speed','m/s',[p('t','Temperature','K',100,1000,10,300),p('m','Molar mass','g/mol',2,100,1,28)],s=>Math.sqrt(3*R*s.t/(s.m/1000)),'Lighter molecules have larger rms speeds at the same temperature. A fourfold temperature increase doubles rms speed. The animation is schematic.','Ideal classical gas; molar mass converted to kg/mol.','Calculate the root-mean-square molecular speed.'),
L('gasenergy','Molecular kinetic energy','gas','⟨E translational⟩ = 3kBT / 2','Mean translational energy','J',[p('t','Temperature','K',100,1000,10,300)],s=>1.5*1.380649e-23*s.t,'Mean translational energy depends on temperature, not molecular mass. Molecules have a distribution of speeds rather than all moving at the rms speed.','Classical gas; three translational degrees of freedom.','Find the average translational kinetic energy per molecule.')],q('At fixed temperature and amount, doubling gas volume makes pressure',['Double','Halve','Quadruple','Unchanged'],1,'PV stays constant under these conditions.')),
Ch(14,'Reflection at curved mirrors','Optics',307,'Spherical mirrors form images by reflection. A real image comes from actual convergence of reflected rays; a virtual image comes from extending those rays backward. Magnification describes image size and orientation.','The diagram uses paraxial rays, not spherical aberration. This lab uses the real-is-positive convention and states it explicitly; compare with the sign convention on the source page.',[
L('mirror','Concave mirror images','mirror','1/f = 1/u + 1/v; m = −v/u','Image distance','cm',[p('u','Object distance','cm',5,100,1,30),p('f','Focal length','cm',5,40,1,15)],s=>Math.abs(s.u-s.f)<1e-9?Infinity:s.f*s.u/(s.u-s.f),'Outside the focus, the image is real and inverted. Inside the focus, it is virtual and upright. At the focus, reflected rays are parallel and there is no finite image distance.','Real-is-positive: u > 0 in front, f > 0 concave, v > 0 real. Paraxial rays.','Find the signed image distance, or identify the infinite-distance case.'),
L('convexmirror','Convex mirror images','mirror','v = fu/(u − f), with f < 0','Image distance','cm',[p('u','Object distance','cm',5,100,1,30),p('f','Signed focal length','cm',-40,-5,1,-15)],s=>s.f*s.u/(s.u-s.f),'A convex mirror produces a virtual upright image smaller than the object. Its negative image distance places the image behind the mirror in this convention.','Real-is-positive convention; spherical paraxial mirror.','Find the signed image distance.'),
L('mirrorR','Curvature and focus','mirror','f = R/2','Focal length magnitude','cm',[p('r','Radius of curvature','cm',10,100,1,40)],s=>s.r/2,'The focus of a spherical mirror is halfway between its pole and centre of curvature for rays close to the principal axis.','Magnitude calculation for a spherical mirror; paraxial limit.','Calculate focal length magnitude.')],q('A concave mirror with the object inside its focus forms a',['Real upright image','Virtual upright image','Real inverted image','No reflected light'],1,'Diverging reflected rays have backward extensions meeting behind the mirror.')),
Ch(15,'Refraction at plane surfaces','Optics',319,'Light changes direction when its speed changes at an interface. Snell’s law connects angles measured from the normal. Total internal reflection can occur only from higher to lower refractive index.','Wave derivations and optical-fibre applications stay as reading. Ray models neglect reflection amplitudes and wave interference.',[
L('snell','Snell’s law','snell','n₁ sin i = n₂ sin r','Refracted angle','°',[p('n1','Incident index','',1,2,.01,1),p('n2','Transmitted index','',1,2,.01,1.5),p('i','Incidence angle','°',0,89,1,40)],s=>{let x=s.n1*Math.sin(rad(s.i))/s.n2;return x>1?NaN:deg(Math.asin(x))},'When n₁sin i exceeds n₂, no transmitted propagating ray exists: total internal reflection replaces ordinary refraction. All angles are measured from the normal.','Flat interface; isotropic transparent media; geometric optics.','Calculate the refracted angle, or identify total internal reflection.'),
L('critical','Critical angle','snell','c = sin⁻¹(n₂/n₁), for n₁ > n₂','Critical angle','°',[p('n1','Denser-medium index','',1.1,2.5,.01,1.5),p('n2','Rarer-medium index','',1,1.09,.01,1)],s=>deg(Math.asin(s.n2/s.n1)),'At the critical angle the transmitted ray travels along the surface. At larger incidence angles, reflection is total in this ideal model.','n₁ > n₂ by construction.','Calculate the critical angle.'),
L('depth','Apparent depth','depth','Apparent depth = real depth × n observer / n medium','Apparent depth','m',[p('d','Real depth','m',.1,5,.1,2),p('n','Medium index','',1,2,.01,1.33)],s=>s.d/s.n,'A submerged object appears shallower when viewed from air near the normal. The relation is an approximation for small viewing angles.','Observer in air, n observer = 1; near-normal rays.','Find apparent depth when viewed from air.')],q('Total internal reflection requires light to travel',['From lower to higher index','From higher to lower index above the critical angle','At normal incidence','Through a mirror'],1,'Both the index direction and the angle condition are necessary.')),
Ch(16,'Refraction through prisms','Optics',336,'A prism changes a ray’s direction at two surfaces. At minimum deviation the internal path is symmetric, with equal angles at the two faces. Small-angle formulas simplify the geometry but have a limited range.','Prism measurements and spectrometer alignment remain practical tasks. The ray tracer reports when the second face causes total internal reflection.',[
L('prism','Trace through a prism','prism','r₁ = asin(sin i/n); r₂ = A − r₁; δ = i + e − A','Deviation angle','°',[p('a','Prism apex angle','°',20,70,1,60),p('n','Prism index','',1.2,1.8,.01,1.5),p('i','Incidence angle','°',20,80,1,50)],s=>{let r1=deg(Math.asin(Math.sin(rad(s.i))/s.n)),r2=s.a-r1,z=s.n*Math.sin(rad(r2));return Math.abs(z)>1?NaN:s.i+deg(Math.asin(z))-s.a},'The first surface bends the ray toward its normal; the second usually bends it away. Some chosen geometries have no emerging ray because of total internal reflection.','Prism in air; exact Snell angles; no reflection losses.','Find the deviation, or identify no emerging ray.'),
L('minimum','Minimum deviation','prism','δ min = 2 asin(n sin(A/2)) − A','Minimum deviation','°',[p('a','Apex angle','°',10,60,1,60),p('n','Refractive index','',1.1,1.8,.01,1.5)],s=>2*deg(Math.asin(s.n*Math.sin(rad(s.a/2))))-s.a,'At minimum deviation the ray passes symmetrically through the prism. This allows refractive index to be determined from a measured apex angle and minimum deviation.','Prism in air; parameter range permits the symmetric transmitted path.','Calculate the minimum deviation.'),
L('thinprism','A thin prism','prism','δ ≈ (n − 1)A','Approximate deviation','°',[p('a','Small apex angle','°',1,10,.5,5),p('n','Refractive index','',1.1,1.8,.01,1.5)],s=>(s.n-1)*s.a,'For small angles, sine and tangent can be approximated by the angle in radians. The same proportional relation holds if both A and δ are expressed in degrees.','Small-angle approximation; prism in air.','Find the approximate deviation of the thin prism.')],q('At minimum deviation in a prism',['The internal angles are unequal','The internal path is symmetric','There is always total reflection','The index equals one'],1,'The internal refraction angles both equal A/2.')),
Ch(17,'Lenses','Optics',345,'A thin lens changes the convergence of a ray bundle. The object position relative to the focus determines whether the image is real or virtual. Optical powers of thin lenses in contact add.','Thick-lens effects, visual-angle experiments and aberrations are outside the thin-lens model. The lab declares a real-is-positive convention to keep signs consistent.',[
L('lens','A converging lens','lens','1/f = 1/u + 1/v; m = −v/u','Image distance','cm',[p('u','Object distance','cm',5,100,1,30),p('f','Focal length','cm',5,40,1,15)],s=>Math.abs(s.u-s.f)<1e-9?Infinity:s.f*s.u/(s.u-s.f),'Beyond the focus the image forms on the other side of the lens and is inverted. Inside the focus, backward ray extensions form an upright virtual image.','Real-is-positive convention: positive object distance; positive f converging; positive v real. Thin paraxial lens.','Find the signed image distance.'),
L('diverging','A diverging lens','lens','v = fu/(u − f), with f < 0','Image distance','cm',[p('u','Object distance','cm',5,100,1,30),p('f','Signed focal length','cm',-40,-5,1,-15)],s=>s.f*s.u/(s.u-s.f),'A diverging lens gives a virtual upright diminished image for a real object. Its negative image distance puts it on the object side.','Thin lens; real-is-positive convention.','Calculate the signed image distance.'),
L('power','Lenses in contact','lens','P total = P₁ + P₂; f = 1/P total','Equivalent power','D',[p('p1','Lens 1 power','D',-10,10,.5,3),p('p2','Lens 2 power','D',-10,10,.5,2)],s=>s.p1+s.p2,'Positive power converges rays; negative power diverges them. A zero sum has infinite equivalent focal length in the ideal thin-lens approximation.','Thin lenses in contact in air; 1 D = 1 m⁻¹.','Find the equivalent optical power.')],q('The power of a converging lens of focal length 0.5 m is',['0.5 D','2 D','−2 D','5 D'],1,'Power is 1/f with f in metres.')),
Ch(18,'Dispersion','Optics',364,'Refractive index depends on wavelength, so a prism separates white light into colours. In normal dispersion violet bends more strongly than red. An achromatic pair reduces colour-dependent focal differences.','Colour bands are illustrative, not a calibrated spectrum. Lens aberration needs wavelength-dependent material data for quantitative prediction.',[
L('dispersion','Separate red and violet','dispersion','Angular separation ≈ (n violet − n red)A','Angular separation','°',[p('a','Thin prism angle','°',1,10,.5,5),p('nr','Red index','',1.3,1.6,.001,1.51),p('difference','Violet−red index','',.001,.08,.001,.02)],s=>s.difference*s.a,'The two colours experience different refractive indices. Greater index difference or prism angle increases the separation in the thin-prism limit.','Thin prism in air; normal dispersion; schematic colours.','Find the angular separation.'),
L('dispersive','Dispersive power','dispersion','ω = (n violet − n red)/(n yellow − 1)','Dispersive power','',[p('ny','Yellow index','',1.3,1.8,.01,1.52),p('difference','Violet−red index','',.001,.08,.001,.02)],s=>s.difference/(s.ny-1),'Dispersive power compares colour separation with the average bending. It is dimensionless and characterizes the material in this approximation.','Normal dispersion; yellow approximates the mean index.','Calculate dispersive power.'),
L('achromat','An achromatic doublet','lens','ω₁P₁ + ω₂P₂ = 0; P₂ = −ω₁P₁/ω₂','Required second-lens power','D',[p('p1','First-lens power','D',1,10,.5,5),p('w1','First dispersive power','',.01,.1,.005,.03),p('w2','Second dispersive power','',.01,.1,.005,.06)],s=>-s.w1*s.p1/s.w2,'The second lens has opposite power to cancel first-order chromatic spread. The pair can still have positive total power if its materials have different dispersive powers.','Thin lenses in contact; first-order achromat condition.','Find the signed power required for the second lens.')],q('In normal dispersion through glass, the colour deviated more is',['Red','Violet','Both equally','Neither'],1,'Violet has the larger refractive index under normal dispersion.')),
Ch(19,'Electric charges','Electricity',378,'Electric charge is conserved and occurs in elementary-charge units. Like charges repel and unlike charges attract. Coulomb’s law gives the force between stationary point charges.','Charging by friction and induction are guided conceptual activities, not material-specific electron-transfer predictions.',[
L('coulomb','Two electric charges','charges','F signed = kq₁q₂ / r²','Signed force factor','N',[p('q1','Charge 1','μC',-10,10,.5,2),p('q2','Charge 2','μC',-10,10,.5,-3),p('r','Separation','m',.1,5,.1,1)],s=>K*s.q1*s.q2*1e-12/(s.r*s.r),'A positive signed factor indicates repulsion; a negative factor indicates attraction. Each body experiences the same force magnitude in opposite directions.','Stationary point charges in vacuum; positive means repulsive.','Calculate the signed Coulomb factor, then classify the interaction.'),
L('quantized','Charge in electron units','charges','Q = −Ne','Net added-electron charge','C',[p('n','Added electrons','',0,100,1,10)],s=>-s.n*1.602176634e-19,'Each added electron contributes −e to net charge. Removing electrons would leave a positive charge. Charge conservation applies to the whole isolated system.','e = 1.602176634 × 10⁻¹⁹ C; initially neutral object.','Find the charge contributed by the added electrons.'),
L('medium','Charges in a dielectric','charges','F signed = kq₁q₂/(εᵣr²)','Signed force factor','N',[p('q1','Charge 1','μC',-10,10,.5,2),p('q2','Charge 2','μC',-10,10,.5,3),p('r','Separation','m',.1,5,.1,1),p('er','Relative permittivity','',1,10,.5,2)],s=>K*s.q1*s.q2*1e-12/(s.er*s.r*s.r),'A uniform dielectric reduces the electrostatic force by its relative permittivity compared with vacuum, under this idealized model.','Infinite homogeneous linear dielectric; no boundaries.','Calculate the signed interaction factor in the dielectric.')],q('Adding electrons to a neutral object makes it',['Positive','Negative','Still neutral','Massless'],1,'Electrons carry negative electric charge.')),
Ch(20,'Electric field','Electricity',387,'An electric field specifies the force per unit positive test charge at a point. Superposition adds field vectors. Field-line arrows show the direction a positive test charge would accelerate, not a particle’s full trajectory.','Field lines and flux surfaces are representations. Gauss’s law requires symmetry to extract a field magnitude easily; irregular charge distributions need numerical solvers.',[
L('field','Field of a point charge','field','E radial = kQ / r²','Radial electric field','N/C',[p('q','Source charge','μC',-10,10,.5,2),p('r','Observation radius','m',.1,5,.1,1)],s=>K*s.q*1e-6/(s.r*s.r),'Positive charge produces outward field and negative charge inward field. Increasing test-charge magnitude changes its force but not the source field.','Isolated point charge in vacuum; outward is positive.','Find the signed radial electric field.'),
L('platefield','Uniform field between plates','capacitor','E = V/d','Electric field magnitude','V/m',[p('v','Plate voltage','V',0,1000,10,100),p('d','Plate separation','mm',1,50,1,10)],s=>s.v/(s.d*.001),'Smaller separation gives a stronger field for the same voltage. Inside large parallel plates the field is approximately uniform away from the edges.','Large parallel plates; fringing neglected.','Calculate field magnitude between the plates.'),
L('flux','Flux through a flat surface','flux','Φ = EA cos θ','Electric flux','N·m²/C',[p('e','Field magnitude','N/C',0,500,10,100),p('a','Surface area','m²',.1,5,.1,2),p('theta','Angle to surface normal','°',0,180,1,60)],s=>s.e*s.a*cosD(s.theta),'Flux counts the component of field crossing the surface. The angle is to the surface normal, not to the surface itself. Flux can be negative when the field enters the chosen orientation.','Uniform field over a planar surface.','Calculate signed electric flux.')],q('Electric field direction is the force direction on a',['Negative test charge','Positive test charge','Neutral object','Photon'],1,'This is the definition of field direction.')),
Ch(21,'Electric potential & energy','Electricity',403,'Potential is energy per unit charge; it is a scalar. Electric field points toward decreasing potential. Potential energy depends on both the potential and the charge placed in it.','Potential is defined relative to a reference. The point-charge model takes zero at infinity and excludes the charge’s singular position.',[
L('potential','Potential of a point charge','potential','V = kQ/r','Electric potential','V',[p('q','Source charge','μC',-10,10,.5,2),p('r','Distance','m',.1,5,.1,1)],s=>K*s.q*1e-6/s.r,'Potential falls as 1/r, more slowly than field magnitude. A negative source charge produces negative potential with zero chosen at infinity.','Point charge in vacuum; reference V = 0 at infinity.','Calculate the signed potential.'),
L('potentialenergy','Energy of a charge','potential','U = qV','Potential energy','J',[p('q','Placed charge','μC',-10,10,.5,2),p('v','Potential','V',-1000,1000,10,500)],s=>s.q*1e-6*s.v,'The same potential gives opposite signed energies for opposite charges. A change in potential energy is q times the change in potential.','Test charge does not substantially alter the source distribution.','Find the signed potential energy.'),
L('gradient','Potential gradient','potential','Eₓ = −ΔV/Δx','Electric field component','V/m',[p('v1','Potential at x = 0','V',-100,100,1,80),p('v2','Potential at x = d','V',-100,100,1,20),p('d','Distance','m',.1,5,.1,2)],s=>-(s.v2-s.v1)/s.d,'The electric field points from higher to lower potential. A constant linear gradient gives a uniform field; equal potentials give zero field in this one-dimensional model.','Potential varies linearly between the two positions.','Calculate the x component of electric field.')],q('Electric potential is a',['Vector','Scalar','Force','Unit of charge'],1,'Potentials add as signed numbers, not vector components.')),
Ch(22,'Capacitors','Electricity',416,'A capacitor stores separated charge and energy. Capacitance depends on geometry and material; charge depends on capacitance and applied voltage. Series and parallel combinations obey different rules.','Dielectric breakdown and fringing require material and geometry data. The model keeps ideal fixed capacitance and never predicts a safe operating voltage.',[
L('capacitance','Build a capacitor','capacitor','C = ε₀εᵣA/d','Capacitance','nF',[p('a','Plate area','cm²',10,1000,10,100),p('d','Separation','mm',.1,10,.1,1),p('er','Relative permittivity','',1,10,.5,1),p('v','Applied voltage','V',0,100,1,12)],s=>EPS*s.er*s.a*1e-4/(s.d*.001)*1e9,'Larger plate area and higher permittivity increase capacitance. Increasing separation decreases it. At fixed voltage, charge Q = CV changes along with capacitance.','Ideal large parallel plates; dielectric fills the gap; no breakdown model.','Find capacitance in nanofarads.'),
L('capenergy','Stored electrical energy','capacitor','U = ½CV²','Stored energy','μJ',[p('c','Capacitance','μF',.1,100,.1,10),p('v','Voltage','V',0,100,1,12)],s=>.5*s.c*s.v*s.v,'At fixed capacitance, doubling voltage quadruples stored energy. This energy can be released when the capacitor discharges.','Ideal capacitor; capacitance independent of voltage.','Calculate stored energy in microjoules.'),
L('capseries','Capacitors in series','circuit','C equivalent = C₁C₂/(C₁ + C₂)','Series capacitance','μF',[p('c1','Capacitor 1','μF',1,100,1,10),p('c2','Capacitor 2','μF',1,100,1,20)],s=>s.c1*s.c2/(s.c1+s.c2),'Series capacitors carry equal charge magnitude; their voltages add. Equivalent series capacitance is smaller than either individual capacitance.','Two ideal capacitors in series.','Find their equivalent series capacitance.')],q('Two equal capacitors C in series have equivalent capacitance',['2C','C/2','C','Zero'],1,'Reciprocals add: 1/Ceq = 2/C.')),
Ch(23,'D.C. circuits','Electricity',431,'Current is charge flow rate. Resistance relates voltage and current for an ohmic component. A real cell loses some voltage across its internal resistance, and resistor networks distribute currents and voltages.','Non-ohmic curves and real-cell chemistry stay as reading. Circuit labs are ideal DC calculations; they are not a general circuit solver.',[
L('ohm','Voltage, resistance & current','circuit','I = V/R; P = VI','Current','A',[p('v','Voltage','V',0,24,.5,12),p('r','Resistance','Ω',1,100,1,10)],s=>s.v/s.r,'A higher voltage drives more current through the same resistor. A larger resistance reduces current at fixed voltage. Power becomes heat in the resistor.','Ohmic resistor with constant resistance.','Calculate the current.'),
L('parallel','Resistors in parallel','circuit','R equivalent = R₁R₂/(R₁ + R₂)','Equivalent resistance','Ω',[p('r1','Resistor 1','Ω',1,100,1,20),p('r2','Resistor 2','Ω',1,100,1,30),p('v','Supply voltage','V',0,24,.5,12)],s=>s.r1*s.r2/(s.r1+s.r2),'Parallel branches have the same voltage. Their currents add; providing another branch reduces total resistance below either branch resistance.','Two ohmic resistors and ideal wires.','Find equivalent resistance.'),
L('cell','A real cell','circuit','I = ℰ/(R + r); V terminal = ℰ − Ir','Circuit current','A',[p('emf','Cell emf','V',1,24,.5,12),p('r','Internal resistance','Ω',0,5,.1,1),p('load','Load resistance','Ω',1,100,1,11)],s=>s.emf/(s.load+s.r),'The terminal voltage decreases as load current rises. Internal power loss is I²r. With no current, the terminal voltage equals the emf.','Constant emf and internal resistance; steady DC.','Calculate current through the load.')],q('Adding another resistor in parallel makes equivalent resistance',['Larger','Smaller','Always zero','Equal to the sum'],1,'A new conducting path raises total conductance.')),
Ch(24,'Nuclear physics','Modern physics',459,'Nuclei contain protons and neutrons. A bound nucleus has less mass than its separated constituents; the mass difference corresponds to binding energy. Nuclear reactions conserve charge and total mass-energy.','Scattering, fission and fusion use conceptual representations. The lab is not a reactor or microscopic nuclear-dynamics simulation. Mass inputs must consistently use either nuclear or atomic conventions.',[
L('binding','Mass defect and binding','nucleus','E binding = Δm × 931.494 MeV/u','Binding energy','MeV',[p('dm','Mass defect','u',0,.5,.001,.0024),p('a','Nucleon number','',1,100,1,2)],s=>s.dm*931.49410242,'A larger mass defect represents a larger total binding energy. Divide by nucleon number to compare binding per nucleon. This comparison helps explain why some reactions release energy.','Use a correctly determined mass defect; 1 u c² = 931.49410242 MeV.','Find the total binding energy.'),
L('nuclearradius','Size of a nucleus','nucleus','R ≈ r₀A¹ᐟ³','Nuclear radius','fm',[p('a','Mass number A','',1,250,1,56),p('r0','Radius constant','fm',1.1,1.3,.01,1.2)],s=>s.r0*Math.cbrt(s.a),'Nuclear volume is approximately proportional to nucleon number, so radius grows with its cube root. The drawing shows schematic nucleons rather than their quantum distribution.','Empirical radius estimate; especially useful beyond very light nuclei.','Estimate the nuclear radius.'),
L('massenergy','Mass into energy','nucleus','E = mc²','Rest energy','J',[p('m','Mass','μg',0,100,1,1)],s=>s.m*1e-9*C0*C0,'Even a small mass corresponds to a large rest energy. A reaction releases the energy associated with its mass difference, not necessarily all the reactants’ rest energy.','Rest mass in micrograms; c = 299792458 m/s.','Calculate the rest-energy equivalent.')],q('Binding energy is the energy required to',['Cool a nucleus','Separate a nucleus into its nucleons','Create only its electrons','Stop its motion'],1,'Binding energy measures the energy difference between bound and separated constituents.')),
Ch(25,'Energy levels','Modern physics',487,'Atomic electrons occupy allowed energies, and transitions exchange photons with energy equal to the level difference. This source chapter also introduces energy bands, semiconductors and doping.','Electron orbits are not literal classical tracks. The hydrogen model is idealized; semiconductor carrier displays do not solve a real junction. Source chapter headings are retained.',[
L('levels','Hydrogen energy levels','levels','Eₙ = −13.6/n² eV','Level energy','eV',[p('n','Principal quantum number','',1,6,1,2)],s=>-13.6/(s.n*s.n),'Levels become closer together as n increases. Zero energy is the ionization limit, so bound levels have negative energy. The diagram is an energy scale, not an orbit map.','Hydrogen approximation; fine structure and external fields omitted.','Find the energy of the selected level.'),
L('transition','Emit a photon','levels','ΔE = 13.6(1/n lower² − 1/n upper²); λ = hc/ΔE','Photon wavelength','nm',[p('lower','Lower level','',1,4,1,2),p('gap','Level-number difference','',1,4,1,1)],s=>1239.841984/(13.6*(1/(s.lower*s.lower)-1/((s.lower+s.gap)**2))),'A downward transition emits a photon whose energy equals the level difference. Higher photon energy corresponds to shorter wavelength. The upper level is lower + gap.','Hydrogen; emission transition; hc = 1239.841984 eV·nm.','Calculate the emitted photon wavelength.'),
L('doping','Semiconductor dopants','bands','N dopant = fraction × N atoms','Dopant density','m⁻³',[p('fraction','Dopant fraction','×10⁻⁸',1,100,1,1),p('density','Host atom density','×10²⁸/m³',1,10,.5,5),p('type','Type: 0 = donor, 1 = acceptor','',0,1,1,0)],s=>s.fraction*1e-8*s.density*1e28,'Donors provide additional conduction electrons; acceptors create holes. Doping changes majority carriers while the sample remains electrically neutral overall.','Dilute dopants; the result counts dopant atoms, not thermally active carrier density.','Calculate the number of dopant atoms per cubic metre.')],q('A hydrogen electron moving to a lower energy level',['Absorbs a photon','Emits a photon','Loses electric charge','Becomes a proton'],1,'The energy decrease is carried away by an emitted photon.')),
Ch(26,'Solids · particles & cosmology','Modern physics',496,'The uploaded book calls this chapter “Solids,” but its content covers antiparticles, quarks, leptons and cosmology. Quark charges add to give hadron charge. Cosmic redshift and Hubble’s law connect observations with expansion.','Particle properties are learning models, not simulated collisions. The expansion analogy is schematic; Hubble’s linear law is for modest redshift, and dark matter and gravitational-wave discussion remain reading.',[
L('quarks','Build proton or neutron','quarks','Q/e = (2N up − N down)/3; N up + N down = 3','Baryon charge','e',[p('up','Up quarks (remaining are down)','',0,3,1,2)],s=>(2*s.up-(3-s.up))/3,'Two up quarks and one down quark give a proton’s +e charge. One up and two down give a neutron’s zero charge. Other combinations need not be stable baryons.','Three valence quarks; up = +2e/3, down = −e/3; no stability prediction.','Calculate the net charge in elementary-charge units.'),
L('hubble','The expanding universe','universe','v recession ≈ H₀d','Recession speed','km/s',[p('h','Hubble parameter','km/(s·Mpc)',50,90,1,70),p('d','Galaxy distance','Mpc',1,500,1,100)],s=>s.h*s.d,'A more distant galaxy has a larger recession speed in the local Hubble relation. Expansion has no special centre: each observer sees other distant galaxies receding in the schematic display.','Low-redshift linear relation; H₀ is an adjustable scenario value, not a fitted measurement.','Use Hubble’s law to estimate recession speed.'),
L('redshift','Cosmic wavelength shift','spectrum','z = (λ observed − λ emitted)/λ emitted','Redshift','',[p('emitted','Emitted wavelength','nm',300,700,1,500),p('ratio','Observed/emitted ratio','',.5,2,.01,1.1)],s=>s.ratio-1,'A positive redshift means observed wavelength is longer. A negative value is a blueshift. Cosmological redshift should not automatically be converted with a classical Doppler formula at large z.','Input wavelengths refer to the same identifiable spectral feature.','Calculate the dimensionless redshift.')],q('The valence quark composition of a proton is',['udd','uud','uuu','ddd'],1,'Two up quarks and one down quark total +1 elementary charge.'))
];
export const initial=lab=>Object.fromEntries(lab.params.map(p=>[p.key,p.value]));
export const metric=(lab,s)=>lab.compute(s);
export function extra(l,s){switch(l.id){
case 'uncertainty':return [['Worst-case ΔA',s.b*s.dl+s.l*s.db,'m²'],['Relative uncertainty',100*(s.dl/s.l+s.db/s.b),'%']];
case 'vector':return [['Horizontal resultant',s.a+s.b*cosD(s.theta),'N'],['Vertical resultant',s.b*sinD(s.theta),'N']];
case 'components':return [['Vertical component',s.a*sinD(s.theta),'N']];
case 'motion':return [['Final velocity',s.u+s.a*s.t,'m/s']];
case 'projectile':return [['Flight time',2*s.u*sinD(s.theta)/s.g,'s'],['Peak height',s.u*s.u*sinD(s.theta)**2/(2*s.g),'m']];
case 'incline':return [['Normal force',s.m*9.8*cosD(s.theta),'N'],['Static limit',s.mus*s.m*9.8*cosD(s.theta),'N'],['Downhill weight',s.m*9.8*sinD(s.theta),'N']];
case 'energy':return [['Average power',l.compute(s)/s.t,'W']];
case 'collision':return [['Kinetic energy lost',.5*s.m1*s.u1**2+.5*s.m2*s.u2**2-.5*(s.m1+s.m2)*l.compute(s)**2,'J']];
case 'circle':return [['Centripetal acceleration',s.v*s.v/s.r,'m/s²'],['Period',2*Math.PI*s.r/s.v,'s']];
case 'angular':return [['Period',2*Math.PI/s.omega,'s']];
case 'orbit':return [['Orbital period',2*Math.PI*(6.371e6+s.h*1000)/l.compute(s)/60,'min'],['Local gravity',G*5.972e24/(6.371e6+s.h*1000)**2,'m/s²']];
case 'spring':return [['Stored energy',.5*s.k*s.x*s.x,'J'],['Period',2*Math.PI*Math.sqrt(s.m/s.k),'s']];
case 'young':return [['Strain',l.compute(s)/1000/s.l,'']];
case 'stress':return [['Strain',l.compute(s)/(s.y*1000),'']];
case 'temperature':return [['Fahrenheit',1.8*s.c+32,'°F']];
case 'latent':return [['Heat absorbed so far',s.fraction*s.m*334000,'J'],['Temperature',0,'°C']];
case 'gas':return [['PV',s.n*R*s.t,'J']];
case 'mirror':case 'convexmirror':case 'lens':case 'diverging':return [['Magnification',-l.compute(s)/s.u,'×']];
case 'power':return [['Equivalent focal length',l.compute(s)===0?Infinity:1/l.compute(s),'m']];
case 'achromat':return [['Combined power',s.p1+l.compute(s),'D']];
case 'capacitance':return [['Stored charge',l.compute(s)*s.v,'nC'],['Stored energy',.5*l.compute(s)*1e-3*s.v*s.v,'μJ']];
case 'ohm':return [['Power dissipated',s.v*s.v/s.r,'W']];
case 'parallel':return [['Branch 1 current',s.v/s.r1,'A'],['Branch 2 current',s.v/s.r2,'A'],['Supply current',s.v/l.compute(s),'A']];
case 'cell':return [['Terminal voltage',s.emf-l.compute(s)*s.r,'V'],['Internal loss',l.compute(s)**2*s.r,'W']];
case 'binding':return [['Binding per nucleon',l.compute(s)/s.a,'MeV/nucleon']];
case 'transition':return [['Photon energy',1239.841984/l.compute(s),'eV'],['Upper level',s.lower+s.gap,'']];
case 'quarks':return [['Down quarks',3-s.up,''],['Baryon number',1,'']];
case 'redshift':return [['Observed wavelength',s.emitted*s.ratio,'nm']];
default:return [];
}}
