import React,{useState,useEffect} from 'react';
import {usePhone} from './responsive.jsx';
import {rcState,pathPoint,pathLength} from './electricity.mjs';
import {fmt} from './canvas.mjs';
const specs=[{key:'v',label:'Supply / initial voltage',unit:'V',min:0,max:24,step:.5},{key:'r',label:'Resistance',unit:'kΩ',min:1,max:100,step:1},{key:'c',label:'Capacitance',unit:'μF',min:10,max:1000,step:10}];
export function ElectricitySandbox({Parameter,useClock,Icon}){
 const [params,setParams]=useState({v:12,r:10,c:100}),[mode,setMode]=useState('charge'),[carrier,setCarrier]=useState('conventional'),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[replay,setReplay]=useClock(running,speed);
 const phone=usePhone();
 const tau=params.r*params.c*.001,position=Math.min(replay,8),f=rcState(params,position/8*5*tau,mode),electrons=carrier==='electrons';
 useEffect(()=>{if(running&&replay>=8){setRunning(false);setReplay(8)}},[running,replay,setReplay]);
 const reset=()=>{setRunning(false);setReplay(0)};
 const paths=[[[100,215],[100,90],[420,90],[420,158]],[[420,188],[420,290],[100,290],[100,245]],...(mode==='discharge'?[[[100,245],[100,215]]]:[])];
 // Integrate current to charge transferred: particles never reverse as current decays.
 const travel=(1-f.decay)*800*(params.v/12)*(params.c/100)*(mode==='charge'?1:-1)*(electrons?-1:1);
 const markers=params.v>0?paths.flatMap((path,j)=>Array.from({length:Math.ceil(pathLength(path)/65)},(_,i)=>{const [x,y]=pathPoint(path,i*65+travel);return <g key={`${j}-${i}`}><circle cx={x} cy={y} r="4" fill={electrons?'#6d98b5':'#d5a155'}/></g>})):[];
 const chartWidth=phone?410:230,chartX=t=>552+t/5*chartWidth,chartY=q=>253-q*135;
 const shownFraction=params.v===0?0:f.fraction,shownDecay=params.v===0?0:f.decay;
 const curve=key=>Array.from({length:101},(_,i)=>{const a=rcState(params,i/100*5*tau,mode);return `${i?'L':'M'}${chartX(i/100*5)},${chartY(params.v===0?0:key==='voltage'?a.fraction:a.decay)}`}).join(' ');
 return <><h1>Follow the charge.<br/><em>See energy build.</em></h1><p>Charge a capacitor through a resistor, then switch to a discharge through the resistor. Follow the leads, watch the plates fill, and compare the voltage and current curves.</p>
 <section className="lab-card"><header className="lab-header"><h3>RC circuit sandbox</h3><span className="status">{position===8?'5 TIME CONSTANTS':running?'IN MOTION':'PAUSED'}</span></header>
 <div className="circuit-controls"><div className="mode-buttons" aria-label="Circuit mode"><button id="rc-charge" className={mode==='charge'?'active':''} aria-pressed={mode==='charge'} onClick={()=>{reset();setMode('charge')}}>Charge</button><button id="rc-discharge" className={mode==='discharge'?'active':''} aria-pressed={mode==='discharge'} onClick={()=>{reset();setMode('discharge')}}>Discharge</button></div><label htmlFor="rc-carrier">Show motion<select id="rc-carrier" value={carrier} onChange={e=>setCarrier(e.target.value)}><option value="conventional">Conventional current · gold</option><option value="electrons">Electron drift · blue</option></select></label></div>
 <div className="drop-stage"><svg id="rc-scene" viewBox={phone?'0 0 530 740':'0 0 840 370'} role="img" aria-label={`${mode==='charge'?'Charging from an initially empty capacitor':'Discharging an initially charged capacitor'}; charge markers follow the conducting leads only. The graph shows capacitor voltage and current magnitude over five time constants.`}>
 <rect width={phone?530:840} height={phone?740:370} fill="#f2f7f4"/>
 <g fill="none" stroke="#86a89a" strokeWidth="3"><path d="M100 215 V90 H420 V158 M420 188 V290 H100 V245"/>{mode==='discharge'?<path d="M100 215 V245"/>:<path d="M100 215 V222 M75 222 H125 M87 238 H113 M100 238 V245"/>}</g>
 <rect x="220" y="75" width="130" height="30" fill="#f6ead5" stroke="#b48444" strokeWidth="2"/><text x="235" y="95" fill="#506b6a" fontSize="13">R = {params.r} kΩ</text>
 <path d="M385 158 H455 M385 188 H455" stroke="#117c72" strokeWidth="5"/><rect x="385" y="162" width="70" height="22" fill="#117c72" opacity={.04+.18*shownFraction}/>
 {Array.from({length:8},(_,i)=><g key={i} opacity={params.v>0?Math.max(0,Math.min(1,f.fraction*8-i)):0}><text x={383+i*10} y="149" fill="#b48444" fontSize="13">+</text><text x={383+i*10} y="210" fill="#6d98b5" fontSize="13">−</text></g>)}
 <text x="280" y="240" fill="#506b6a" fontSize="13">C = {params.c} μF</text><text x="280" y="264" fill="#117c72" fontSize="16" id="rc-plate-voltage">V꜀ = {fmt(f.voltage)} V</text>
 {mode==='charge'?<g fill="#506b6a" fontSize="13"><text x="64" y="216">+</text><text x="66" y="247">−</text><text x="35" y="273">{params.v} V source</text></g>:<text x="40" y="330" fill="#506b6a" fontSize="13">Source disconnected · stored energy drives current</text>}
 <g data-testid="rc-markers">{markers}</g>
 <text x="62" y="45" fill="#117c72" fontSize="13">{mode==='charge'?'SOURCE → CAPACITOR':'CAPACITOR → RESISTOR'}</text>
 <text x="62" y="355" fill="#506b6a" fontSize="12">{electrons?'Electron drift is opposite to conventional current.':'Conventional current follows positive charge direction.'}</text>
 <g data-testid="rc-chart-panel" className="transient-panel" transform={phone?'translate(-485 370)':undefined}><line x1="525" y1="25" x2="525" y2="345" stroke="#d2dfd5"/>
 <text x="552" y="45" fill="#117c72" fontSize="13">THE TRANSIENT</text><text x="552" y="78" fill="#506b6a" fontSize="13">{phone?'Voltage and current · normalized':'Fractions of supply voltage and initial current'}</text>
 <g stroke="#d2dfd5" fill="none"><path d={`M552 108 V253 H${552+chartWidth+8}`}/>{[0,.5,1].map(v=><line key={v} x1="552" y1={chartY(v)} x2={552+chartWidth} y2={chartY(v)} strokeDasharray="3 5"/>)}</g>
 <g fill="#506b6a" fontSize="12"><text x="535" y="122">1</text><text x="535" y="257">0</text>{[0,1,2,3,4,5].map(t=><text key={t} x={chartX(t)-5} y="273">{t}τ</text>)}</g>
 <path d={curve('voltage')} fill="none" stroke="#117c72" strokeWidth="3"/><path d={curve('current')} fill="none" stroke="#b48444" strokeWidth="3" strokeDasharray={mode==='discharge'?'5 5':undefined}/>
 <line x1={chartX(f.time/tau)} y1="108" x2={chartX(f.time/tau)} y2="253" stroke="#7998a7" strokeDasharray="3 5"/>
 <circle data-testid="rc-voltage-dot" cx={chartX(f.time/tau)} cy={chartY(shownFraction)} r="5" fill="#117c72"/><circle cx={chartX(f.time/tau)} cy={chartY(shownDecay)} r="4" fill="#b48444"/>
 <text x="552" y="303" fill="#117c72" fontSize="13">Green: V꜀ / V₀</text><text x="552" y="326" fill="#b48444" fontSize="13">Gold: |I| / I₀</text><text x="552" y="350" fill="#506b6a" fontSize="12">Discharge curves coincide; gold is dashed.</text></g>
 </svg></div>
 <div className="canvas-toolbar"><button id="rc-play" className="primary" aria-pressed={running} disabled={position===8} onClick={()=>setRunning(!running)}><Icon name={running?'pause':'play'}/>{running?'Pause':'Play'}</button><button id="rc-restart" onClick={reset}><Icon name="reset"/>Restart</button><span className="helper" id="rc-time">t = {fmt(f.time)} s · {fmt(f.time/tau)}τ</span></div>
 <div className="playback-controls"><label htmlFor="rc-speed">Playback speed<select id="rc-speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.25}>0.25×</option><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><label className="replay-control" htmlFor="rc-seek">Explore the transient<input id="rc-seek" type="range" min="0" max="8" step=".01" value={position} onChange={e=>{setRunning(false);setReplay(Number(e.target.value))}}/></label><p className="animation-readout">Eight playback seconds represent 5τ = {fmt(5*tau)} physical seconds. The time scale adjusts to R and C. Marker motion is schematic; its slowing follows the decaying current.</p></div>
 <div className="control-panel">{specs.map(p=><Parameter key={p.key} param={p} value={params[p.key]} onChange={v=>{reset();setParams(s=>({...s,[p.key]:Math.max(p.min,Math.min(p.max,v))}))}}/>)}</div>
 <div className="equation-box"><div><div className="field-label">{mode==='charge'?'Charging from zero voltage':'Discharging from V₀'}</div><div className="formula">{mode==='charge'?'V꜀ = V₀(1 − e⁻ᵗ/ᴿᶜ)':'V꜀ = V₀e⁻ᵗ/ᴿᶜ'}</div></div><div className="output"><div className="field-label">Capacitor voltage</div><div className="value" id="rc-voltage">{fmt(f.voltage)}<span className="unit">V</span></div></div></div>
 <div className="metric-strip">{[['Current magnitude',Math.abs(f.current)*1000,'mA','rc-current'],['Plate charge |Q|',f.charge*1e6,'μC','rc-charge-value'],['Stored energy',f.energy*1000,'mJ','rc-energy'],['Time constant τ',tau,'s','rc-tau'],['Resistor heating',f.power*1000,'mW','rc-power']].map(([label,value,unit,id])=><div className="metric-item" key={id}><small>{label}</small><strong id={id}>{fmt(value)} <span className="helper">{unit}</span></strong></div>)}</div>
 <p className="live-text" id="rc-status">{params.v===0?'Zero voltage: no charge transfer and no stored energy.':mode==='charge'?'Current deposits equal and opposite charge on the plates. As capacitor voltage rises, the voltage across the resistor and the current fall.':'The initially charged capacitor supplies current in the reverse direction. Its stored energy becomes heat in the resistor.'}</p>
 </section><div className="split"><div className="card"><h3>One time constant</h3><p>At t = τ, charging reaches 63.2% of V₀; discharging retains 36.8%. After 5τ, charging reaches 99.3%. Double R or C to double the physical time needed. Current is largest at the start and decays exponentially.</p><button onClick={()=>{setRunning(false);setReplay(8/5)}} id="rc-one-tau">Inspect t = τ →</button></div><div className="card assumption"><h3>What the model means</h3><p>Ideal capacitor, constant resistor, ideal DC source, and negligible wire resistance. Charges move in the conducting leads and accumulate on the plates; they do not cross the insulating gap. Discharge starts from V₀, removes the source and connects the resistor across the capacitor. Electron markers show drift direction, not microscopic motion or signal propagation speed.</p></div></div><button onClick={()=>{location.hash='chapter/23/ohm/lab'}}>Explore steady DC and parallel branches →</button></>;
}
