import {initial,G,K,EPS,R,C0} from './content.mjs';
import {fmt} from './canvas.mjs';
export function makeQuestion(l,random=Math.random){let s={};for(let p of l.params){let x=p.min+(p.max-p.min)*(.15+random()*.7);x=p.min+Math.round((x-p.min)/p.step)*p.step;s[p.key]=Number(Math.min(p.max,Math.max(p.min,x)).toFixed(9))}return {params:s,expected:l.compute(s)}}
export function checkAnswer(expected,input){let a=input.trim().toLowerCase().replace(/−/g,'-');if(Number.isNaN(expected))return /^(tir|total internal reflection|no ray|no transmitted ray|no emerging ray)$/.test(a);if(!Number.isFinite(expected))return /^(infinity|inf|∞|at infinity)$/.test(a);if(!a)return false;let n=Number(a);if(!Number.isFinite(n))return false;let tolerance=expected===0?1e-8:Math.abs(expected)*.01;return Math.abs(n-expected)<=tolerance}
export function substitution(l,s){let v=l.compute(s);if(l.id==='snell'){let x=s.n1*Math.sin(s.i*Math.PI/180)/s.n2;return `sin r = ${fmt(s.n1)} × sin(${fmt(s.i)}°) ÷ ${fmt(s.n2)} = ${fmt(x)}.\n${x>1?'Since sin r would exceed 1, there is total internal reflection.':`r = asin(${fmt(x)}) = ${fmt(v)}°.`}`}
 if(l.id==='prism'){let r1=Math.asin(Math.sin(s.i*Math.PI/180)/s.n)*180/Math.PI,r2=s.a-r1,z=s.n*Math.sin(r2*Math.PI/180);return `r₁ = asin(sin(${s.i}°)/${s.n}) = ${fmt(r1)}°.\nr₂ = ${s.a}° − ${fmt(r1)}° = ${fmt(r2)}°.\nsin e = ${s.n} × sin(${fmt(r2)}°) = ${fmt(z)}.\n${Math.abs(z)>1?'No emerging ray: total internal reflection at the second face.':`e = ${fmt(Math.asin(z)*180/Math.PI)}°.\nδ = i + e − A = ${fmt(v)}°.`}`}
 if(['lens','mirror','diverging','convexmirror'].includes(l.id)){return `${s.u===s.f?'u = f: the denominator is zero, so the image is at infinity.':`v = (${s.f} × ${s.u}) / (${s.u} − ${s.f}) = ${fmt(v)} cm.\nm = −v/u = ${fmt(-v/s.u)}.\n${v>0?'Positive v: real, inverted image.':'Negative v: virtual, upright image.'}`}`}
 if(l.id==='incline'){let limit=Math.tan(s.theta*Math.PI/180),mu=s.mus*s.ratio;return `tan(${s.theta}°) = ${fmt(limit)}; μₛ = ${s.mus}.\n${limit<=s.mus?'Static friction can hold the block: a = 0.':`The block slides; μₖ = μₛ × ratio = ${fmt(mu)}.\na = 9.8[sin(${s.theta}°) − ${fmt(mu)}cos(${s.theta}°)] = ${fmt(v)} m/s².`}`}
 let fn=l.compute.toString();let expr=fn.slice(fn.indexOf('=>')+2).trim();expr=expr.replace(/s\.([a-z0-9]+)/gi,(_,key)=>`(${fmt(s[key])})`).replace(/\bG\b/g,G.toString()).replace(/\bK\b/g,K.toString()).replace(/\bEPS\b/g,EPS.toString()).replace(/\bR\b/g,R.toString()).replace(/\bC0\b/g,C0.toString()).replace(/rad\((\([^)]*\))\)/g,'($1 × π/180)').replace(/deg\((.*)\)/g,'($1 × 180/π)').replaceAll('sinD','sin°').replaceAll('cosD','cos°').replaceAll('Math.sqrt','√').replaceAll('Math.cbrt','cuberoot').replaceAll('Math.sin','sin').replaceAll('Math.cos','cos').replaceAll('Math.asin','asin').replaceAll('Math.exp','exp').replaceAll('Math.max','max').replaceAll('**','^').replaceAll('*',' × ').replaceAll('/',' ÷ ');
 return `${expr}\n= ${fmt(v)} ${l.unit}\nTrigonometric calculations use radians internally. Conversion factors in the expression convert the displayed units.`;
}
