import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseHTML} from 'linkedom';
import {chapters,initial} from './content.mjs';
import {handlesFor} from './interactions.mjs';
import {makeQuestion} from './exercise.mjs';
const {window,document}=parseHTML('<html><body><div id="app"></div></body></html>');
let store=new Map,frames=new Map,nextFrame=1,now=0,drawCalls=[];
document.oninput=null;
const mobileQuery={matches:false,listeners:new Set,addEventListener(type,fn){this.listeners.add(fn)},removeEventListener(type,fn){this.listeners.delete(fn)}};
const drawerQuery={...mobileQuery,listeners:new Set};
Object.assign(globalThis,{window,document,location:{hash:'#home'},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},IS_REACT_ACT_ENVIRONMENT:true,matchMedia:q=>q.includes('1024px')?drawerQuery:q.includes('max-width')?mobileQuery:{matches:false},devicePixelRatio:1,performance:{now:()=>now},requestAnimationFrame:cb=>{let id=nextFrame++;frames.set(id,cb);return id},cancelAnimationFrame:id=>frames.delete(id)});
window.scrollTo=()=>{};
globalThis.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('dist/book.json'))});
class Ctx{measureText(s){return {width:[...s].length*7}}createLinearGradient(){return {addColorStop(){}}}}
for(let m of ['setLineDash','fillText','clearRect','fillRect','strokeRect','beginPath','closePath','moveTo','lineTo','arc','ellipse','rect','clip','fill','stroke','save','restore','translate','rotate','setTransform'])Ctx.prototype[m]=function(...args){if(this.scene)drawCalls.push([m,...args])};
globalThis.OffscreenCanvas=class{getContext(){return new Ctx}};window.HTMLCanvasElement.prototype.getContext=function(){let c=new Ctx;c.scene=this.id==='scene';return c};
window.Element.prototype.getBoundingClientRect=()=>({left:0,top:0,width:840,height:370});window.Element.prototype.setPointerCapture=()=>{};window.Element.prototype.releasePointerCapture=()=>{};
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this.querySelector('option[selected]')?.value||this.querySelector('option')?.value||''},set(v){for(let o of this.querySelectorAll('option'))v===o.value?o.setAttribute('selected',''):o.removeAttribute('selected')}});
// Match the browser's textarea.defaultValue reflection, which LinkeDOM omits.
Object.defineProperty(window.HTMLTextAreaElement.prototype,'defaultValue',{get(){return this.textContent},set(v){this.textContent=v}});
Math.random=()=>.5;
// Import React DOM only after the DOM globals exist, so its event support detection uses this DOM.
const {act}=await import('react');
await act(async()=>{await import('./app-runtime.mjs')});
const $=id=>document.getElementById(id);
async function go(hash){await act(async()=>{location.hash=hash;window.dispatchEvent(new window.Event('hashchange'))})}
async function event(el,type,props={}){assert.ok(el,`missing element for ${type}`);await act(async()=>{let e=new window.Event(type,{bubbles:true,cancelable:true});Object.assign(e,props);el.dispatchEvent(e)})}
const click=el=>event(el,'click');
async function input(el,value){await act(async()=>{const setter=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(el,value);else el.value=value;el.dispatchEvent(new window.Event('input',{bubbles:true}))})}
async function step(n=1){for(let i=0;i<n;i++)await act(async()=>{now+=50;const pending=[...frames.entries()];frames.clear();for(const [,cb] of pending)cb(now)})}
assert.equal(document.querySelectorAll('.chapter-tile').length,26);assert.ok($('begin-drop'));
let labRoutes=0,drags=0;
for(const chapter of chapters){for(const lab of chapter.labs){await go('#'+`chapter/${chapter.id}/${lab.id}/lab`);assert.ok($('scene'));assert.ok($('graph'));assert.equal(document.querySelectorAll('.control').length,lab.params.length);
  await click($('capture'));assert.equal($('clear-baseline').disabled,false);await click($('predict'));assert.equal($('result-value').textContent,'Make a prediction');await click($('predict'));await click($('reset'));
  const handles=handlesFor(lab,initial(lab));assert.equal(document.querySelectorAll('[data-handle]').length,handles.length);
  if(handles.length){const h=handles[0];await event(document.querySelector(`[data-handle="${h.id}"]`),'pointerdown',{pointerId:7,button:0,clientX:h.x,clientY:h.y});await event(document.querySelector('.drag-layer'),'pointermove',{pointerId:7,clientX:h.x+30,clientY:h.y+25});await event(document.querySelector('.drag-layer'),'pointerup',{pointerId:7});const key=h.keys[0];assert.notEqual(Number($('num-'+key).value),initial(lab)[key],lab.id+' drag updates parameter');drags++;await click($('reset'))}
  await go('#'+`chapter/${chapter.id}/${lab.id}/practice`);const q=makeQuestion(lab,()=>.5);await input($('answer'),Number.isNaN(q.expected)?'TIR':!Number.isFinite(q.expected)?'infinity':String(q.expected));await event($('answer-form'),'submit');assert.ok($('feedback').textContent.startsWith('✓ Correct'),lab.id+' checked answer');await click(document.querySelector(`[data-quiz="${chapter.quiz.answer}"]`));assert.ok($('quiz-feedback').textContent.startsWith('✓ Correct'));await click($('load-question'));await go('#'+`chapter/${chapter.id}/${lab.id}/lab`);assert.equal(Number($('num-'+lab.params[0].key).value),q.params[lab.params[0].key]);labRoutes++;
}await go(`#chapter/${chapter.id}/${chapter.labs[0].id}/read`);assert.ok($('source-text').textContent.length>500);await input($('reader-search'),'zzzzunlikely');assert.equal($('source-text').textContent,'No matching passages.');await go(`#chapter/${chapter.id}/${chapter.labs[0].id}/exercises`);assert.ok(document.querySelector('.source-question'));await click(document.querySelector('[data-review]'));assert.ok(document.querySelector('[data-review]').textContent.includes('Reviewed'));
}
// Real draw-coordinate assertions across advancing frames, including pause and unmount cleanup.
await go('#chapter/3/projectile/lab');assert.equal($('play').textContent,'Play');await click($('play'));drawCalls=[];await step();let first=drawCalls.filter(c=>c[0]==='arc'&&c[3]===8).at(-1);drawCalls=[];await step(10);let later=drawCalls.filter(c=>c[0]==='arc'&&c[3]===8).at(-1);assert.ok(later[1]>first[1]);assert.ok(later[2]<first[2]);await click($('play'));drawCalls=[];await step(3);assert.equal(drawCalls.length,0);await click($('restart'));assert.equal($('animation-time').textContent,'Animation: 0.0 s');
await go('#chapter/2/vector/lab');await event(document.querySelector('[data-handle="b"]'),'pointerdown',{pointerId:12,button:0,clientX:245,clientY:183});await event(document.querySelector('.drag-layer'),'pointermove',{pointerId:12,clientX:245,clientY:155});await event(document.querySelector('.drag-layer'),'pointerup',{pointerId:12});assert.equal(Number($('num-b').value),10);assert.equal(Number($('num-theta').value),90);assert.ok($('result-value').textContent.startsWith('12.81'));await event(document.querySelector('[data-handle="b"]'),'keydown',{key:'ArrowUp',shiftKey:true});assert.equal(Number($('num-theta').value),91);
// Real playback rate and scrubbing, with no surprise restart on pause.
await go('#chapter/4/newton/lab');assert.ok($('playback-speed'));await act(async()=>{$('playback-speed').value='0.25';$('playback-speed').dispatchEvent(new window.Event('change',{bubbles:true}))});await click($('play'));await step(12);assert.ok(Math.abs(Number($('replay-position').value)-.15)<1e-8,'quarter speed advances 0.15 seconds in 0.6 seconds');await input($('replay-position'),'1.5');assert.equal($('play').textContent,'Play');assert.equal($('animation-time').textContent,'Animation: 1.5 s');assert.ok($('animation-readout').textContent.includes('t = 1.5 s'));const seeked=$('animation-readout').textContent;await step(5);assert.equal($('animation-readout').textContent,seeked);await click($('restart'));assert.equal($('animation-time').textContent,'Animation: 0.0 s');
for(const [chapter,id] of [[4,'incline'],[5,'work'],[5,'energy'],[5,'collision'],[11,'cooling'],[12,'conduction'],[12,'radiation'],[14,'mirror'],[16,'snell'],[18,'lens'],[25,'transition']]){let actual=chapters.find(c=>c.labs.some(l=>l.id===id));await go(`#chapter/${actual.id}/${id}/lab`);assert.ok($('play'),id+' exposes playback');await click($('play'));await step(10);assert.notEqual($('animation-time').textContent,'Animation: 0.0 s');await click($('play'));}
// Optical images: formed pictures follow signed magnification and selected geometry.
await go('#chapter/17/lens/lab');assert.ok(document.querySelector('[data-testid="lens-silhouette"]'));assert.ok(document.querySelector('[data-testid="optics-formed-image"]').getAttribute('transform').includes('scale(-1 -1)'));await input($('num-u'),'10');assert.ok($('optics-image-caption').textContent.includes('Virtual, upright'));assert.ok(document.querySelector('[data-testid="optics-formed-image"]').getAttribute('transform').includes('scale(3 3)'));await input($('num-u'),'15');assert.equal(document.querySelector('[data-testid="optics-formed-image"]'),null);assert.ok($('optics-image-caption').textContent.includes('no finite image'));await click($('predict'));assert.ok($('optics-image-caption').textContent.includes('Reveal the outcome'));
await go('#light');assert.equal(document.querySelectorAll('[data-optics-mode]').length,6);const convexShape=document.querySelector('[data-testid="lens-silhouette"]').getAttribute('d');await click(document.querySelector('[data-optics-mode="diverging"]'));assert.notEqual(document.querySelector('[data-testid="lens-silhouette"]').getAttribute('d'),convexShape);assert.ok($('optics-image-caption').textContent.includes('Virtual, upright'));await click(document.querySelector('[data-optics-mode="plane"]'));assert.ok(document.querySelector('[data-testid="optics-formed-image"]').getAttribute('transform').includes('scale(-1 1)'));assert.ok($('optics-image-caption').textContent.includes('mirror-reversed'));await input($('num-u'),'60');assert.ok(document.querySelector('[data-testid="optics-object"]').getAttribute('transform').includes('translate(100 200)'));assert.ok(document.querySelector('[data-testid="optics-formed-image"]').getAttribute('transform').includes('translate(700 200)'));
for(const mode of ['mirror','convexmirror','depth']){await click(document.querySelector(`[data-optics-mode="${mode}"]`));assert.ok($('optics-image-scene'));assert.ok(document.querySelector('[data-testid="optics-formed-image"]'))}await input($('num-n'),'2');assert.ok($('optics-image-caption').textContent.includes('1 m rather than 2 m'));
const original=document.querySelector('[data-testid="optics-object"] image').getAttribute('href');Object.defineProperty($('optics-upload'),'files',{configurable:true,value:[{type:'text/plain',size:1}]});await event($('optics-upload'),'change');assert.ok(document.querySelector('[role="alert"]').textContent.includes('PNG, JPEG or WebP'));globalThis.FileReader=class{readAsDataURL(){this.result='data:image/png;base64,aGVsbG8=';this.onload()}};Object.defineProperty($('optics-upload'),'files',{configurable:true,value:[{type:'image/png',size:50}]});await event($('optics-upload'),'change');assert.equal(document.querySelector('[data-testid="optics-object"] image').getAttribute('href'),'data:image/png;base64,aGVsbG8=');assert.equal(document.querySelector('[data-testid="optics-formed-image"] image').getAttribute('href'),'data:image/png;base64,aGVsbG8=');await click($('optics-sample'));assert.equal(document.querySelector('[data-testid="optics-object"] image').getAttribute('href'),original);
// One upload is shared by every sandbox mode and chapter picture panel.
const uploaded='data:image/png;base64,aGVsbG8=';
Object.defineProperty($('optics-upload'),'files',{configurable:true,value:[{type:'image/png',size:50}]});await event($('optics-upload'),'change');
for(const mode of ['lens','diverging','plane','mirror','convexmirror','depth']){
 await click(document.querySelector(`[data-optics-mode="${mode}"]`));
 for(const image of document.querySelectorAll('#optics-image-scene image'))assert.equal(image.getAttribute('href'),uploaded);
}
for(const route of ['#chapter/17/lens/lab','#chapter/17/diverging/lab','#chapter/15/mirror/lab','#chapter/16/depth/lab','#home','#light']){
 await go(route);
 for(const image of document.querySelectorAll('#optics-image-scene image'))assert.equal(image.getAttribute('href'),uploaded);
}
await click($('optics-sample'));await go('#chapter/17/lens/lab');assert.equal(document.querySelector('[data-testid="optics-object"] image').getAttribute('href'),original);
// Quarks support direct play without changing their conserved composition.
await go('#chapter/26/quarks/lab');
let quark=document.querySelector('[data-quark="0"]');const quarkX=quark.querySelector('circle').getAttribute('cx');
await event(quark,'keydown',{key:'ArrowRight'});assert.notEqual(quark.querySelector('circle').getAttribute('cx'),quarkX);
await event(quark,'keydown',{key:'Home'});assert.equal(quark.querySelector('circle').getAttribute('cx'),quarkX);
const quarkSvg=document.querySelector('.quark-play');quarkSvg.getBoundingClientRect=()=>({left:0,top:0,width:840,height:370});
await event(quark,'pointerdown',{pointerId:71,button:0});await event(quarkSvg,'pointermove',{pointerId:71,clientX:1000,clientY:1000});await event(quarkSvg,'pointerup',{pointerId:71});
assert.ok(Math.hypot(Number(quark.querySelector('circle').getAttribute('cx'))-255,Number(quark.querySelector('circle').getAttribute('cy'))-180)<=65.001);
assert.equal($('result-value').textContent,'1e');await input($('num-up'),'1');assert.ok(document.querySelector('[data-quark="1"]').getAttribute('aria-label').startsWith('Down'));assert.equal($('result-value').textContent,'0e');
// Electricity: actual charge markers respond to switch/current, and RC frames use exact live values.
await go('#chapter/23/ohm/lab');await click($('play'));drawCalls=[];await step(10);assert.ok(drawCalls.some(c=>c[0]==='arc'&&c[3]===4));await click($('circuit-switch'));assert.equal($('result-value').textContent,'0A');assert.ok($('animation-readout').textContent.includes('I = 0 A'));drawCalls=[];await step(3);assert.equal(drawCalls.filter(c=>c[0]==='arc'&&c[3]===4).length,6,'open switch has only two stationary terminal dots per frame');await click($('circuit-switch'));assert.ok($('result-value').textContent.startsWith('1.2'));await act(async()=>{$('carrier-mode').value='electrons';$('carrier-mode').dispatchEvent(new window.Event('change',{bubbles:true}))});assert.ok($('animation-readout').textContent.includes('Electrons drift opposite'));
await go('#charge');assert.equal($('rc-play').textContent,'Play');assert.equal($('rc-voltage').textContent,'0V');assert.equal($('rc-current').textContent,'1.2 mA');assert.equal(frames.size,0);await click($('rc-play'));const beforeRc=document.querySelector('[data-testid="rc-markers"] circle').getAttribute('cy');await step(10);assert.notEqual($('rc-voltage').textContent,'0V');assert.notEqual(document.querySelector('[data-testid="rc-markers"] circle').getAttribute('cy'),beforeRc);await click($('rc-play'));const rcPaused=$('rc-time').textContent;await step(5);assert.equal($('rc-time').textContent,rcPaused);await click($('rc-one-tau'));assert.equal($('rc-time').textContent,'t = 1 s · 1τ');assert.ok($('rc-voltage').textContent.startsWith('7.585'));await click($('rc-discharge'));assert.equal($('rc-voltage').textContent,'12V');assert.equal($('rc-play').textContent,'Play');await click($('rc-one-tau'));assert.ok($('rc-voltage').textContent.startsWith('4.415'));await input($('rc-seek'),'8');assert.equal($('rc-play').disabled,true);await click($('rc-restart'));assert.equal($('rc-play').disabled,false);await input($('num-r'),'20');assert.equal($('rc-tau').textContent,'2 s');assert.equal($('rc-current').textContent,'0.6 mA');await input($('num-v'),'0');assert.equal(document.querySelectorAll('[data-testid="rc-markers"] circle').length,0);assert.equal($('rc-energy').textContent,'0 mJ');await input($('rc-seek'),'4');assert.equal(document.querySelector('[data-testid="rc-voltage-dot"]').getAttribute('cy'),'253','zero supply has a zero-voltage graph');await input($('num-v'),'12');await click($('rc-charge'));await act(async()=>{$('rc-speed').value='2';$('rc-speed').dispatchEvent(new window.Event('change',{bubbles:true}))});await click($('rc-play'));await step(82);assert.equal($('rc-play').textContent,'Play');assert.equal($('rc-play').disabled,true);assert.equal(frames.size,0,'RC stops at five time constants');await click($('rc-restart'));await click($('rc-play'));await go('#home');assert.equal(frames.size,0,'RC unmount cancels playback');assert.ok($('begin-charge'));
// Drop using pointer capture/release, then check the actual body's coordinates and landing.
await go('#drop');let body=document.querySelector('[data-testid="mass-body"]');const mass=document.querySelector('[data-testid="drop-mass"]'),svg=$('drop-scene');await event(mass,'pointerdown',{pointerId:9,button:0,clientX:260,clientY:164});await event(svg,'pointermove',{pointerId:9,clientX:300,clientY:112});assert.equal(Number($('num-height').value),8);assert.equal(Number(document.querySelector('[data-testid="mass-body"]').getAttribute('cx')),300);await event(svg,'pointerup',{pointerId:9});const startY=Number(document.querySelector('[data-testid="mass-body"]').getAttribute('cy'));await step(10);assert.ok(Number(document.querySelector('[data-testid="mass-body"]').getAttribute('cy'))>startY);await click($('drop-pause'));const paused=$('drop-time').textContent;await step(5);assert.equal($('drop-time').textContent,paused);await click($('drop-pause'));await step(40);assert.ok($('drop-status').textContent.startsWith('Landed'));assert.equal($('drop-height').textContent,'0 m');assert.equal(Number(document.querySelector('[data-testid="mass-body"]').getAttribute('cy')),320);await click($('drop-reset'));assert.equal($('drop-speed').textContent,'0 m/s');await click($('drop-release'));await go('#home');assert.equal(frames.size,0,'unmount cancels animation');
await go('#chapter/1/units/exercises');const note=document.querySelector('[data-note]');await act(async()=>{const setter=Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value')?.set;setter.call(note,'Working saved from React');note.dispatchEvent(new window.Event('input',{bubbles:true}))});assert.ok([...store.values()].some(s=>s.includes('Working saved from React')),'notes persist');await go('#home');await go('#chapter/1/units/exercises');assert.equal(document.querySelector('[data-note]').value,'Working saved from React');
await go('#plan');assert.equal(document.querySelectorAll('tbody tr').length,26);await go('#home');assert.equal($('progress-number').textContent,'100%');assert.ok([...store.values()].some(v=>v.includes('"sourceDone"')));
await input($('search'),'zzzznochapter');assert.ok(document.querySelector('.nav-empty').textContent.includes('No chapters match'));await input($('search'),'');assert.equal(document.querySelectorAll('.chapter-link').length,26);
await act(async()=>{mobileQuery.matches=true;drawerQuery.matches=true;for(const fn of [...mobileQuery.listeners,...drawerQuery.listeners])fn()});assert.ok($('sidebar').hasAttribute('inert'),'closed mobile navigation cannot take focus');await click($('menu'));assert.equal($('sidebar').hasAttribute('inert'),false);assert.ok(document.querySelector('main').hasAttribute('inert'));assert.ok(document.querySelector('.nav-backdrop'));await click(document.querySelector('.nav-close'));assert.ok($('sidebar').hasAttribute('inert'));assert.equal(document.querySelector('main').hasAttribute('inert'),false);
// Phone layouts must keep the full diagram, chart and energy panels reachable.
assert.equal(document.body.style.overflow,'');await click($('menu'));assert.equal(document.body.style.overflow,'hidden');assert.equal($('sidebar').getAttribute('aria-modal'),'true');await event(window,'keydown',{key:'Escape'});assert.notEqual(document.body.style.overflow,'hidden');assert.ok($('sidebar').hasAttribute('inert'));
await go('#chapter/2/vector/lab');assert.equal($('scene').width,530);assert.equal($('graph').width,420);assert.equal(document.querySelector('.drag-layer').getAttribute('viewBox'),'0 0 530 370');const phoneLayer=document.querySelector('.drag-layer');phoneLayer.getBoundingClientRect=()=>({left:10,top:20,width:320,height:320*370/530});await event(document.querySelector('[data-handle="b"]'),'pointerdown',{pointerId:41,button:0,clientX:150,clientY:100});await event(phoneLayer,'pointermove',{pointerId:41,clientX:10+245*320/530,clientY:20+155*320/530});await event(phoneLayer,'pointerup',{pointerId:41});assert.equal(Number($('num-b').value),10);assert.equal(Number($('num-theta').value),90,'phone-sized pointer coordinates stay aligned with the vector');
await go('#drop');assert.equal($('drop-scene').getAttribute('viewBox'),'0 0 530 740');assert.equal(document.querySelector('[data-testid="drop-energy-panel"]').getAttribute('transform'),'translate(-480 370)');$('drop-scene').getBoundingClientRect=()=>({left:0,top:0,width:320,height:320*740/530});await event(document.querySelector('[data-testid="drop-mass"]'),'pointerdown',{pointerId:42,button:0,clientX:260*320/530,clientY:164*320/530});await event($('drop-scene'),'pointermove',{pointerId:42,clientX:300*320/530,clientY:112*320/530});await event($('drop-scene'),'pointerup',{pointerId:42});assert.equal(Number($('num-height').value),8);assert.equal(Number(document.querySelector('[data-testid="mass-body"]').getAttribute('cx')),300);await step(40);assert.ok($('drop-status').textContent.startsWith('Landed'));
await go('#charge');assert.equal($('rc-scene').getAttribute('viewBox'),'0 0 530 740');assert.equal(document.querySelector('[data-testid="rc-chart-panel"]').getAttribute('transform'),'translate(-485 370)');await click($('rc-one-tau'));assert.ok($('rc-voltage').textContent.startsWith('7.585'),'phone chart and state use the same model');
await go('#light');assert.equal($('optics-image-scene').getAttribute('viewBox'),'0 0 430 390');for(const id of ['optics-object','optics-formed-image']){const transform=document.querySelector(`[data-testid="${id}"]`).getAttribute('transform'),x=Number(transform.match(/translate\(([^ ]+)/)[1]);assert.ok(x>30&&x<400,'object and formed image fit the phone viewport')}await click(document.querySelector('[data-optics-mode="depth"]'));assert.equal($('optics-image-scene').getAttribute('viewBox'),'0 0 430 780');assert.equal(document.querySelector('[data-testid="depth-apparent-panel"]').getAttribute('transform'),'translate(0 390)');
await act(async()=>{mobileQuery.matches=false;drawerQuery.matches=false;for(const fn of [...mobileQuery.listeners,...drawerQuery.listeners])fn()});assert.equal($('optics-image-scene').getAttribute('viewBox'),'0 0 840 390');assert.equal(document.querySelector('[data-testid="depth-apparent-panel"]').getAttribute('transform'),'translate(375 0)');await go('#chapter/2/vector/lab');assert.equal($('scene').width,840);assert.equal($('graph').width,840);assert.equal(document.querySelector('.drag-layer').getAttribute('viewBox'),'0 0 840 370');assert.equal($('sidebar').hasAttribute('inert'),false);
await act(async()=>{drawerQuery.matches=true;for(const fn of drawerQuery.listeners)fn()});assert.ok($('sidebar').hasAttribute('inert'),'tablet uses a drawer');assert.equal($('scene').width,840,'tablet retains the wide diagram');await click($('menu'));assert.equal(document.body.style.overflow,'hidden');await click(document.querySelector('.nav-backdrop'));assert.equal($('sidebar').hasAttribute('inert'),true);await act(async()=>{drawerQuery.matches=false;for(const fn of drawerQuery.listeners)fn()});
console.log('PASS: responsive Canvas/SVG dimensions, phone vector and mass touch coordinates, complete stacked circuit/energy/depth panels, optics image fit, orientation changes and drawer scroll locking.');
console.log(`PASS: React renders all ${labRoutes} laboratories/practice routes and 26 readers/notebooks; ${drags} pointer drags update state; keyboard vector controls, projectile frames, pause/restart, mass drag/drop/landing and animation cleanup. DOM tests; browser visual QA remains unavailable.`);
